import type { Service } from "@/lib/types";

export const services: Service[] = [
  {
    slug: "ai-lead-site",
    number: "01",
    title: "Lead-Gen Website & AI Search",
    group: "Lead-Gen Websites & AI Search",
    category: "Lead-Gen Websites",
    icon: "lead-site",
    heroEyebrow: "Lead-Gen Websites",
    focusKeyword: "lead gen websites",
    shortDescription:
      "A fast, clear website that explains your offer, ranks on Google, gets cited by AI search, and turns visitors into calls, forms, and bookings.",
    whatItIs:
      "A high-converting website on Next.js or Webflow, built so Google, ChatGPT, and Perplexity can find and cite your business. Schema markup, AI-search-ready copy, Core Web Vitals performance, and a structure that turns traffic into booked calls. MVP launches with your core offer pages and lead capture live, then we iterate on content, case studies, and conversion paths based on real traffic data.",
    deliverables: [
      "Funnel mapping workshop (one primary conversion goal)",
      "Custom homepage & offer page design in Figma",
      "MVP site on Next.js or Webflow (core pages live)",
      "Mobile-first responsive build",
      "Schema markup (Organization, Service, FAQ)",
      "llms.txt & AI-citation-ready page structure",
      "AI-search-ready copy for hero, services, and FAQ blocks",
      "CRM-connected forms with instant lead alerts",
      "Google Analytics 4 + conversion events",
      "Core Web Vitals pass on launch pages",
      "Staging review before production cutover",
      "30-day post-MVP fixes & iteration sprint",
      "Phase-2 roadmap (blog, case studies, programmatic SEO)",
    ],
    idealClients: [
      "Service businesses whose site doesn't convert or show up in AI answers",
      "Clinics, local services, and professional firms that need more booked calls",
      "Teams on WordPress or Webflow ready to move to a faster Next.js stack",
    ],
    processSteps: [
      {
        step: 1,
        title: "Map the funnel",
        description:
          "We run a working session to define the single action every page should drive (call, form, or booking), then map the page hierarchy and lead capture flow backward from that goal.",
        icon: "discovery",
        deliverables: [
          "Conversion goal workshop",
          "Page hierarchy & URL map",
          "Lead capture flow diagram",
          "Competitor & keyword snapshot",
        ],
      },
      {
        step: 2,
        title: "Design the system",
        description:
          "We design in Figma around your offer and buyer journey, not a template. Hero, proof, offer clarity, and one primary CTA per page before a single line of code is written.",
        icon: "design",
        deliverables: [
          "Homepage & core offer page designs",
          "Mobile-first layout specs",
          "Copy framework for hero, services, FAQ",
          "Design review & revision round",
        ],
      },
      {
        step: 3,
        title: "Build for speed & AI search",
        description:
          "We build on Next.js or Webflow with Core Web Vitals, schema markup, llms.txt, and direct-answer blocks from the first commit, so Google and AI engines can find and cite your business on launch day.",
        icon: "build",
        deliverables: [
          "Production-ready Next.js or Webflow build",
          "Schema markup (Organization, Service, FAQ)",
          "llms.txt & AI-citation page structure",
          "Core Web Vitals pass on launch pages",
          "GA4 + conversion event tracking",
        ],
      },
      {
        step: 4,
        title: "Wire the capture & launch",
        description:
          "Forms connect to your CRM with instant notification. We run a staging review, cut over to production, and stay on for 30 days to fix anything that breaks and iterate on what the data shows.",
        icon: "launch",
        deliverables: [
          "CRM-connected forms with instant lead alerts",
          "Staging review & client sign-off",
          "Production cutover",
          "30-day post-launch fixes & iteration sprint",
          "Phase-2 roadmap (blog, case studies, programmatic SEO)",
        ],
      },
    ],
    results: [
      "Sub-2-second load on mobile, the make-or-break for paid traffic",
      "Every lead in your CRM within seconds of submitting",
      "Pages structured to be cited in Google AI Overviews, ChatGPT, and Perplexity",
    ],
    problems: [],
    subServices: [
      {
        title: "AI-Cited Lead Gen Site",
        description:
          "A fast Next.js or Webflow site structured with schema, llms.txt, and direct-answer blocks so ChatGPT and Perplexity can cite your business.",
        icon: "lead-site",
        span: "2x1",
      },
      {
        title: "Website Redesign",
        description:
          "Rebuild around your offer and buyer journey, not a template. Hero, proof, offer clarity, and one primary CTA per page.",
        icon: "design",
      },
      {
        title: "Landing & Offer Pages",
        description:
          "Focused pages for consults, promotions, and lead capture. Each with a single conversion goal and CRM-connected forms.",
        icon: "build",
      },
      {
        title: "Service & Local SEO Pages",
        description:
          "Location and service-line pages that rank for the terms buyers search, with schema markup and internal linking built in.",
        icon: "seo",
      },
      {
        title: "SEO & AEO Content",
        description:
          "Blog posts, FAQ blocks, and direct-answer content structured to rank on Google and get cited in AI Overviews.",
        icon: "seo",
        span: "1x2",
      },
      {
        title: "Schema, FAQ & llms.txt Setup",
        description:
          "Technical setup so Google and AI tools parse your offer: Organization, Service, FAQ schema, and llms.txt on every launch.",
        icon: "build",
      },
      {
        title: "Performance Cleanup",
        description:
          "Fix slow loads, Core Web Vitals failures, and broken conversion paths on existing sites before or after a redesign.",
        icon: "launch",
        span: "2x1",
      },
    ],
    values: [
      { title: "Speed over decoration", description: "We ship the page that loads in under two seconds, not the one that wins a design award and bounces visitors." },
      { title: "One goal per page", description: "Every page drives one action. We design backward from the conversion, not forward from a template." },
      { title: "Citation-ready structure", description: "Schema, llms.txt, and direct-answer blocks ship on day one so AI engines can actually find you." },
      { title: "Measure what books calls", description: "We track form fills, calls, and booked appointments, not vanity traffic." },
    ],
    testimonials: [
      {
        quote: "Our new site loads instantly and finally shows up in ChatGPT answers. We're booking consults from it every week.",
        author: "Dr. Lena Park",
        role: "Owner, Park Dental Wellness",
        rating: 5,
      },
      {
        quote: "The redesign paid for itself in 30 days. Leads land in our CRM instantly instead of sitting in an inbox.",
        author: "Marcus Webb",
        role: "Founder, Webb HVAC",
        rating: 5,
      },
    ],
    relatedServices: ["crm-pipeline-automation", "seo-aeo-content", "ai-receptionist"],
    faqs: [
      {
        question: "How long does a lead-gen website take to launch?",
        answer:
          "Most projects launch in 7–10 business days for an MVP with core offer pages, lead capture, and CRM connection live. Larger sites with multiple service lines or programmatic SEO pages typically take 2–4 weeks.",
      },
      {
        question: "Do you build on Next.js or Webflow?",
        answer:
          "Both. We recommend Next.js + Sanity when you want maximum speed, AI-search structure, and a content system that scales. Webflow works well for simpler sites or teams already on that stack.",
      },
      {
        question: "Will my site show up in ChatGPT and Google AI Overviews?",
        answer:
          "We structure every page with schema markup, direct-answer blocks, FAQ schema, and llms.txt so AI engines can parse and cite your business. Rankings and citations depend on your market, but the technical foundation is built in from day one.",
      },
      {
        question: "What happens to my leads after someone fills out a form?",
        answer:
          "Every form submission creates a CRM contact instantly and sends a mobile alert to your team. We wire HubSpot, GoHighLevel, or Salesforce depending on what you already use.",
      },
      {
        question: "Can you redesign my existing site without losing SEO?",
        answer:
          "Yes. We map every existing URL, set up 301 redirects, preserve schema and content equity, and launch on a faster stack without dropping rankings.",
      },
      {
        question: "What's included in the starting price?",
        answer:
          "Funnel mapping, custom design, MVP build on Next.js or Webflow, schema & AI-search setup, CRM-connected forms, GA4 tracking, staging review, production launch, and 30 days of post-launch fixes.",
      },
    ],
    pricingSignal: "From $3,500 setup · Optional support from $349/mo",
    timeline: "Typical launch: 7–10 business days",
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1600&auto=format&fit=crop",
    order: 1,
  },
  {
    slug: "ai-receptionist",
    number: "03",
    title: "AI Receptionist & Booking Automation",
    group: "AI Receptionist & Booking Automation",
    category: "AI Receptionist",
    icon: "receptionist",
    heroEyebrow: "AI Receptionist",
    focusKeyword: "ai receptionist",
    shortDescription:
      "AI voice and chat assistants that answer common questions, capture lead details, book appointments, text back missed calls, and hand off to a person when needed.",
    whatItIs:
      "A 24/7 AI voice or chat system that answers inbound inquiries, qualifies leads, books appointments, and sends instant text-back to missed calls before they call your competitor. Built on Vapi, Retell, or Twilio with CRM logging, call summaries, and human escalation rules. MVP goes live with your top call scenarios handled, then we tune scripts, add services, and expand hours based on real call logs.",
    deliverables: [
      "Call & chat intake script workshop",
      "AI voice or chat agent for top 5 call types",
      "Missed-call SMS within 60 seconds",
      "Lead qualification questions & routing rules",
      "Calendar booking for qualified callers",
      "CRM or GoHighLevel contact creation",
      "Business-hours & after-hours behavior rules",
      "Human escalation triggers for complex calls",
      "Call summary logged to CRM after each interaction",
      "Test call suite before go-live",
      "48-hour post-MVP script tuning",
      "Monthly performance review & iteration option",
    ],
    idealClients: [
      "Dental, medical, and wellness clinics with busy front desks",
      "HVAC, plumbing, and roofing teams who can't answer while on a job",
      "Legal, real estate, and professional services where the first callback wins",
    ],
    processSteps: [
      { step: 1, title: "Script the intake", description: "We map the questions that qualify a lead and the answers that book the job.", icon: "script", deliverables: ["Call scenario workshop", "Qualification question script", "Booking flow diagram", "Tone and escalation guidelines"] },
      { step: 2, title: "Build the agent", description: "Voice or chat agent configured to your services, hours, and tone.", icon: "agent", deliverables: ["AI voice or chat agent for top call types", "Calendar integration", "CRM contact creation", "Test call suite"] },
      { step: 3, title: "Wire missed-call text-back", description: "Every unanswered call triggers an instant SMS within seconds.", icon: "wire", deliverables: ["Missed-call SMS within 60 seconds", "After-hours behavior rules", "Owner notification on high-intent leads", "Message templates for approval"] },
      { step: 4, title: "Set escalation rules", description: "High-value or complex calls route to a human, the rest book themselves.", icon: "escalate", deliverables: ["Human escalation triggers", "Call summary logged to CRM", "48-hour post-launch script tuning", "Performance review checklist"] },
    ],
    results: [
      "Missed calls answered by SMS in under 60 seconds",
      "Qualified appointments booked while your team works",
      "Fewer leads lost to the next contractor on the list",
    ],
    pricingSignal: "From $1,200 setup + $299/mo · Usage billed separately",
    timeline: "Typical launch: 1–3 business days",
    image:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1600&auto=format&fit=crop",
    order: 3,
  },
  {
    slug: "crm-pipeline-automation",
    number: "02",
    title: "CRM & Follow-Up Automation",
    group: "CRM & Follow-Up Automation",
    category: "CRM & Follow-Up",
    icon: "crm",
    heroEyebrow: "CRM & Follow-Up",
    focusKeyword: "crm follow-up automation",
    shortDescription:
      "Every form, call, booking request, and message gets captured, assigned, followed up with, and tracked until it becomes a booked call or customer.",
    whatItIs:
      "Full CRM setup on HubSpot, GoHighLevel, or Salesforce with automated pipeline stages, lead routing, form-to-CRM connection, booking-to-CRM connection, email follow-up, SMS follow-up, missed-lead follow-up, appointment reminders, review request automation, and owner notification flows. Your team stops managing the tool and starts closing deals.",
    deliverables: [
      "Pipeline audit & stage definition workshop",
      "CRM workspace setup (HubSpot, GHL, or Salesforce)",
      "Deal stages with clear entry/exit criteria",
      "Form-to-CRM connection with instant lead alerts",
      "Booking-to-CRM connection",
      "Email & SMS follow-up sequences per stage",
      "Missed-lead and stale-lead re-engagement flows",
      "Appointment reminders (SMS & email)",
      "Review request automation after job completion",
      "Owner notification flows for new leads",
      "Pipeline value & velocity dashboard",
      "30-day adoption check-in & workflow tweaks",
    ],
    idealClients: [
      "Clinics and service businesses whose leads sit in inboxes",
      "Owners who can't see pipeline value without asking three people",
      "Teams whose follow-up is inconsistent or manual",
    ],
    processSteps: [
      { step: 1, title: "Audit the pipeline", description: "We map how a lead actually moves from first touch to closed deal.", icon: "audit", deliverables: ["Pipeline audit workshop", "Lead source inventory", "Current workflow map", "Gap analysis report"] },
      { step: 2, title: "Architect the stages", description: "Clear stages with entry and exit criteria, no ambiguity about what's next.", icon: "architect", deliverables: ["Deal stage definitions", "Entry and exit criteria per stage", "Ownership and routing rules", "Pipeline dashboard wireframe"] },
      { step: 3, title: "Automate the busywork", description: "Tasks, follow-ups, and reminders fire automatically as deals progress.", icon: "automate", deliverables: ["Form-to-CRM connection", "Email and SMS follow-up sequences", "Missed-lead re-engagement flows", "Owner notification automations"] },
      { step: 4, title: "Train the team", description: "We document the workflow and train your team so adoption sticks.", icon: "train", deliverables: ["Workflow documentation", "Team training session", "30-day adoption check-in", "Workflow tweak sprint"] },
    ],
    results: [
      "Every lead captured, assigned, and followed up with automatically",
      "Follow-up sequences that run whether or not anyone remembers",
      "A pipeline number you can trust at a glance",
    ],
    pricingSignal: "From $2,500 setup · Optional support from $299–$549/mo",
    timeline: "Typical launch: 3–7 business days",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop",
    order: 2,
  },
  {
    slug: "outbound-lead-gen",
    number: "—",
    title: "Outbound Lead Gen Automation",
    group: "CRM & Follow-Up Automation",
    category: "CRM & Follow-Up",
    icon: "outbound",
    shortDescription: "A system that puts only warm leads in front of your sales team.",
    whatItIs:
      "Scraping, enrichment, and AI-personalized outreach at scale. We build the system, prospect lists, personalization layers, and multi-channel sequences so your sales team only talks to warm leads.",
    deliverables: [
      "ICP definition & buyer persona workshop",
      "Prospect list build (500–2,000 contacts)",
      "Email & LinkedIn data enrichment pipeline",
      "AI-personalized opening lines per segment",
      "3-touch email sequence (MVP campaign live)",
      "LinkedIn connection & follow-up templates",
      "Reply detection & warm-lead routing to sales",
      "Unsubscribe & compliance setup (CAN-SPAM)",
      "Campaign performance dashboard",
      "A/B test on subject lines in week two",
      "Scale playbook for additional segments",
      "Optional monthly list refresh & copy iteration",
    ],
    idealClients: [
      "B2B teams whose outbound is manual and impossible to scale",
      "Founders doing their own prospecting between everything else",
      "Agencies and professional service firms who need predictable pipeline",
    ],
    processSteps: [
      { step: 1, title: "Define the ICP", description: "We get specific about who buys, so the list is sharp from the start." },
      { step: 2, title: "Build and enrich", description: "Prospect lists scraped and enriched with the data that drives reply rates." },
      { step: 3, title: "Personalize at scale", description: "AI writes the opening line that makes each message feel hand-written." },
      { step: 4, title: "Run and manage", description: "Multi-channel sequences run, replies route to your team to close." },
    ],
    results: [
      "A repeatable list-to-reply pipeline instead of guesswork",
      "Personalization at volume without a team of SDRs",
      "Warm replies in your inbox, not cold lists to grind through",
    ],
    pricingSignal: "Starting from $3,000 setup + $500/mo management",
    timeline: "MVP in 2–3 business days · iterate & maintain after launch",
    image:
      "https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=1600&auto=format&fit=crop",
    order: 11,
  },
  {
    slug: "seo-aeo-content",
    number: "—",
    title: "SEO & AI Search Content",
    group: "Lead-Gen Websites & AI Search",
    category: "Lead-Gen Websites",
    icon: "seo",
    shortDescription: "Rank on Google and get cited in AI answers.",
    whatItIs:
      "We build the content and technical infrastructure to rank on Google and appear in AI-generated answers across ChatGPT, Perplexity, and Google AI Overviews. Schema markup, llms.txt, programmatic pages, and content that earns citations.",
    deliverables: [
      "Technical SEO crawl & priority fix list",
      "Core Web Vitals remediation on key templates",
      "Schema markup (Article, FAQ, LocalBusiness as needed)",
      "llms.txt & robots.txt tuned for AI crawlers",
      "Keyword map for 10–20 priority terms",
      "5 MVP content briefs with search intent notes",
      "2 publish-ready articles in MVP launch",
      "Internal linking structure for topic clusters",
      "Google Search Console & Bing setup",
      "AI-search formatting (direct answers, FAQ blocks)",
      "Monthly content calendar for phase 2",
      "Ranking & citation tracking dashboard",
    ],
    idealClients: [
      "Businesses invisible on Google for the terms that matter",
      "Brands not yet cited in ChatGPT and Perplexity answers",
      "Teams publishing content that never ranks or converts",
    ],
    processSteps: [
      { step: 1, title: "Audit the foundation", description: "We fix the technical issues quietly capping your rankings." },
      { step: 2, title: "Structure for answers", description: "Schema and llms.txt make your content legible to AI engines." },
      { step: 3, title: "Research and brief", description: "We target terms with intent and brief content that earns citations." },
      { step: 4, title: "Publish and compound", description: "Monthly articles that build authority instead of one-off posts." },
    ],
    results: [
      "Rankings for terms your buyers actually search",
      "Citations in AI Overviews and answer engines",
      "Content that compounds in value month over month",
    ],
    pricingSignal: "Starting from $2,500 strategy + $1,500/mo content",
    timeline: "MVP in 2–3 business days · iterate & maintain after launch",
    image:
      "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?q=80&w=1600&auto=format&fit=crop",
    order: 12,
  },
  {
    slug: "ops-automation",
    number: "—",
    title: "Internal Ops Automation",
    group: "CRM & Follow-Up Automation",
    category: "CRM & Follow-Up",
    icon: "ops",
    shortDescription: "Eliminate the manual tasks quietly killing your team's time.",
    whatItIs:
      "We map your internal workflows, find the manual tasks killing your team's time, and automate them with n8n or Make. Reporting, document processing, scheduling, and internal notifications, handled automatically.",
    deliverables: [
      "Workflow audit & time-waste map",
      "Automation spec for highest-ROI process first",
      "n8n or Make workflow (MVP automation live)",
      "Error handling & failure notifications",
      "Test cases for edge cases & empty data",
      "Runbook for your team to monitor runs",
      "Slack or email alert on workflow failure",
      "Documentation with trigger & action diagram",
      "Second workflow scoped in phase-2 roadmap",
      "30-day monitoring & bug-fix window",
      "Optional retainer for new workflows each month",
      "Training call to hand off ownership",
    ],
    idealClients: [
      "Teams copy-pasting data between tools every single day",
      "Operators whose reporting eats hours every week",
      "Businesses scaling headcount to handle work software should do",
    ],
    processSteps: [
      { step: 1, title: "Audit the workflow", description: "We watch how work actually moves and flag the manual chokepoints." },
      { step: 2, title: "Design the automation", description: "We map each task to a trigger, an action, and a fallback." },
      { step: 3, title: "Build and test", description: "Workflows built in n8n or Make, tested against real edge cases." },
      { step: 4, title: "Document and hand off", description: "Every workflow comes with an SOP so your team owns it." },
    ],
    results: [
      "Hours of weekly manual work removed per workflow",
      "Reports that build and send themselves",
      "Fewer errors from copy-paste and missed steps",
    ],
    pricingSignal: "Starting from $2,000 per workflow package",
    timeline: "MVP in 1–2 business days per workflow · iterate after launch",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop",
    order: 13,
  },
  {
    slug: "custom-ai-agents",
    number: "—",
    title: "Custom AI Agents",
    group: "AI Receptionist & Booking Automation",
    category: "AI Receptionist",
    icon: "agents",
    shortDescription: "Purpose-built agents for your knowledge, sales, and support.",
    whatItIs:
      "Purpose-built AI agents for your specific business: internal knowledge bases, sales enablement tools, support deflection bots, and document processing agents. Built on Claude API, OpenAI, or open-source models depending on your needs.",
    deliverables: [
      "Use-case workshop & success criteria definition",
      "Model selection memo (Claude, OpenAI, or open-source)",
      "Knowledge base ingestion (docs, URLs, PDFs)",
      "Agent with 3–5 core tools wired in MVP",
      "System prompt & guardrail configuration",
      "Human handoff path for low-confidence answers",
      "Staging test suite (20+ real scenarios)",
      "Production deployment & access controls",
      "Usage & cost monitoring dashboard",
      "Weekly accuracy review in first month",
      "Phase-2 tool additions roadmap",
      "Runbook for prompt updates without a developer",
    ],
    idealClients: [
      "Teams whose knowledge lives in one person's head",
      "Support queues full of questions a bot could answer",
      "Operations buried in documents that need reading and routing",
    ],
    processSteps: [
      { step: 1, title: "Scope the use case", description: "We pin down the job to be done before writing a single prompt." },
      { step: 2, title: "Select the model", description: "Claude, OpenAI, or open-source, chosen for cost, speed, and accuracy." },
      { step: 3, title: "Build and integrate", description: "The agent gets the tools and data it needs to actually be useful." },
      { step: 4, title: "Test and monitor", description: "We harden it against failure modes and watch it in production." },
    ],
    results: [
      "Answers in seconds from sources that were buried",
      "Support volume deflected before it reaches a human",
      "Documents processed and routed without manual reading",
    ],
    pricingSignal: "Starting from $4,000",
    timeline: "MVP in 5–10 business days · iterate & maintain after launch",
    image:
      "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1600&auto=format&fit=crop",
    order: 14,
  },
  {
    slug: "custom-in-house-software-for-smbs",
    number: "04",
    title: "Custom In-House Software for SMBs",
    group: "Custom In-House Software for SMBs",
    category: "Custom In-House Software",
    icon: "dashboards",
    heroEyebrow: "Custom In-House Software",
    focusKeyword: "custom in-house software for SMBs",
    shortDescription: "Portals, dashboards, and internal tools built for teams outgrowing spreadsheets.",
    whatItIs:
      "Custom client portals, staff dashboards, booking systems, and internal workflow tools built for SMB teams that have outgrown spreadsheets and email threads. We connect your existing stack, design views your team actually uses, and ship software you own.",
    deliverables: [
      "Discovery workshop to map workflows and data sources",
      "Source system audit (CRM, billing, scheduling, analytics)",
      "Role-based access and permissions model",
      "Client or patient portal with secure login",
      "Staff dashboard with live KPIs and task views",
      "Booking system with confirmations and CRM logging",
      "Document upload and approval flows",
      "Reporting dashboard pulled from your existing tools",
      "Mobile-friendly access for owners and field teams",
      "Admin panel for records, orders, and team workflows",
      "Handoff documentation and team training",
      "Optional monthly improvements on retainer",
    ],
    idealClients: [
      "Owners pulling numbers from five tools to see one picture",
      "Teams making decisions on week-old spreadsheets",
      "Operators who want one screen that tells the truth",
    ],
    processSteps: [
      { step: 1, title: "Audit the sources", description: "We inventory every tool that holds a number you care about.", icon: "audit", deliverables: ["KPI workshop", "Source system audit", "Data quality review", "MVP metric shortlist"] },
      { step: 2, title: "Build the pipeline", description: "Data flows automatically from each source into one place.", icon: "pipeline", deliverables: ["Data pipeline for MVP metrics", "Daily refresh schedule", "Error handling and alerts", "Source connection documentation"] },
      { step: 3, title: "Design the view", description: "The metrics that drive decisions, front and center, nothing else.", icon: "dashboard", deliverables: ["Executive dashboard design", "Mobile-friendly owner view", "Role-based access setup", "Dashboard walkthrough recording"] },
      { step: 4, title: "Refresh and alert", description: "Daily refresh plus alerts when a number crosses a threshold.", icon: "refresh", deliverables: ["Threshold alerts on key metrics", "Missing-data flags", "Phase-2 metrics roadmap", "Handoff and training session"] },
    ],
    results: [
      "One screen for pipeline, spend, traffic, and revenue",
      "Decisions made on today's data, not last week's",
      "Alerts that surface problems before they cost you",
    ],
    pricingSignal: "Starting from $1,500",
    timeline: "MVP in 2–3 business days · iterate & maintain after launch",
    image:
      "https://images.unsplash.com/photo-1543286386-713bdd548da4?q=80&w=1600&auto=format&fit=crop",
    order: 4,
  },
  {
    slug: "review-reputation",
    number: "—",
    title: "Review & Reputation Automation",
    group: "CRM & Follow-Up Automation",
    category: "CRM & Follow-Up",
    icon: "reviews",
    shortDescription: "Your Google reputation on autopilot.",
    whatItIs:
      "An automated system that requests Google reviews at the right moment, responds with AI-assisted replies, flags negative feedback, and feeds your local SEO strategy. Your reputation on autopilot.",
    deliverables: [
      "Review request trigger mapped to your job-complete event",
      "SMS & email review ask templates (on-brand)",
      "Google Business Profile audit & quick wins",
      "AI-drafted reply templates for 1–5 star reviews",
      "Negative review private alert to owner/manager",
      "Review velocity tracking dashboard",
      "Competitor review benchmark snapshot",
      "Staff script for in-person review asks",
      "MVP live on one location or service line",
      "Phase-2 rollout to additional locations",
      "Monthly reputation summary report",
      "Ongoing copy & timing optimization option",
    ],
    idealClients: [
      "Local businesses leaving five-star reviews on the table",
      "Owners who forget to ask happy customers at the right moment",
      "Teams with no system to catch a bad review before it spreads",
    ],
    processSteps: [
      { step: 1, title: "Time the ask", description: "We trigger review requests at the moment satisfaction peaks." },
      { step: 2, title: "Optimize the profile", description: "Your Google Business Profile gets tuned for local ranking." },
      { step: 3, title: "Draft the replies", description: "AI drafts on-brand responses to every review for quick approval." },
      { step: 4, title: "Catch the negatives", description: "Negative feedback is flagged privately before it goes public." },
    ],
    results: [
      "A steady flow of new Google reviews each month",
      "Faster, consistent replies that improve local ranking",
      "Early warning on unhappy customers before they post",
    ],
    pricingSignal: "Starting from $800 setup + $199/mo",
    timeline: "MVP in 1 business day · iterate & maintain after launch",
    image:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1600&auto=format&fit=crop",
    order: 16,
  },
  {
    slug: "ai-systems-retainer",
    number: "05",
    title: "Monthly Support & Improvements",
    group: "Monthly Support & Improvements",
    category: "Monthly Support",
    icon: "retainer",
    heroEyebrow: "Monthly Support",
    focusKeyword: "monthly website support",
    shortDescription:
      "Monthly support for the website, CRM automations, AI receptionist, dashboards, forms, integrations, and reporting after launch.",
    whatItIs:
      "A monthly partnership after launch. We maintain, iterate, and expand your website, CRM automations, AI receptionist, dashboards, and integrations, adding new automations, improving agents, A/B testing sequences, and staying ahead of what's breaking or underperforming.",
    deliverables: [
      "Monthly strategy call (priorities & backlog)",
      "Unlimited small fixes on live automations (<2hr each)",
      "One new automation or agent improvement per month",
      "Performance report on key workflows & agents",
      "24-hour SLA on break/fix issues",
      "Proactive monitoring alerts setup",
      "A/B tests on sequences & landing pages",
      "Quarterly stack audit & deprecation cleanup",
      "Documentation kept current as systems change",
      "Roadmap for next 90 days of improvements",
      "Direct Slack or email channel to your builder",
      "Rollover unused build credit (within quarter)",
    ],
    idealClients: [
      "Businesses that want their systems to keep improving",
      "Owners who don't want to manage another vendor relationship",
      "Teams who'd rather expand the stack than babysit it",
    ],
    processSteps: [
      { step: 1, title: "Monthly strategy", description: "We meet to prioritize what moves the number this month.", icon: "strategy", deliverables: ["Monthly strategy call", "Prioritized backlog", "90-day improvement roadmap", "Success metrics agreed"] },
      { step: 2, title: "Ship one build", description: "At least one new automation or agent improvement every month.", icon: "ship", deliverables: ["One shipped improvement", "Release notes", "Before and after metric snapshot", "Documentation update"] },
      { step: 3, title: "Fix and tune", description: "Unlimited small fixes and A/B tests on what's already live.", icon: "tune", deliverables: ["Break/fix within 24-hour SLA", "Small fixes under 2 hours each", "A/B test on one live asset", "Monitoring alert review"] },
      { step: 4, title: "Report and repeat", description: "Performance reporting so you always know what the stack returns.", icon: "report", deliverables: ["Monthly performance report", "Workflow health summary", "Next month build recommendation", "Stack audit notes"] },
    ],
    results: [
      "A stack that improves every month instead of decaying",
      "Priority response with a 24-hour SLA",
      "One less vendor to chase, one more system that compounds",
    ],
    pricingSignal: "Basic from $349/mo · Growth from $549/mo · Partner from $1,500/mo",
    timeline: "Monthly partnership after launch",
    image:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1600&auto=format&fit=crop",
    order: 6,
  },
  {
    slug: "platform-migrations",
    number: "06",
    title: "Platform Migrations",
    group: "Platform Migrations",
    category: "Platform Migrations",
    icon: "migration",
    heroEyebrow: "Platform Migrations",
    focusKeyword: "platform migrations",
    shortDescription:
      "Move from Webflow, WordPress, Framer, Wix, or Squarespace to Next.js + Sanity without losing SEO or content.",
    whatItIs:
      "We migrate your site from a legacy CMS to Next.js + Sanity without losing SEO equity, redirects, or content. URL structure preserved, redirects in place, content restructured for the new stack, and a launch plan that keeps Google rankings stable.",
    deliverables: [
      "Current site audit & redirect map",
      "Content inventory and restructuring plan",
      "Next.js + Sanity build (core pages)",
      "URL redirect strategy (301s preserved)",
      "Schema markup carried over or upgraded",
      "llms.txt & AI-citation structure",
      "Staging review against current site",
      "Production cutover with zero downtime",
      "Post-launch SEO ranking check",
      "30-day post-migration fixes sprint",
    ],
    idealClients: [
      "Teams stuck on a slow CMS that caps their SEO",
      "Businesses outgrowing Webflow or WordPress",
      "Companies that need a faster, more flexible stack",
    ],
    processSteps: [
      { step: 1, title: "Audit the current site", description: "We inventory URLs, content, redirects, and SEO equity before anything moves.", icon: "audit", deliverables: ["URL and content inventory", "SEO equity audit", "Redirect requirement list", "Migration risk report"] },
      { step: 2, title: "Map the redirects", description: "Every URL gets a destination so no ranking or backlink is lost.", icon: "architect", deliverables: ["301 redirect map", "Legacy URL mapping", "Content restructuring plan", "Stakeholder sign-off"] },
      { step: 3, title: "Rebuild on Next.js", description: "Core pages rebuilt on a faster stack with Sanity for content.", icon: "build", deliverables: ["Next.js + Sanity core pages", "Schema markup migration", "llms.txt and AI structure", "Staging environment for review"] },
      { step: 4, title: "Cutover safely", description: "Production switch with zero downtime and a ranking check after launch.", icon: "launch", deliverables: ["Zero-downtime cutover plan", "Production launch", "Post-launch ranking check", "30-day fix sprint"] },
    ],
    results: [
      "No rankings or backlinks lost in the move",
      "A faster, more flexible stack your team can actually edit",
      "Content structured for AI citation from day one",
    ],
    pricingSignal: "From $3,500 setup · Scope depends on page count",
    timeline: "Typical migration: 2–4 weeks",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop",
    order: 5,
  },
];
