import type { Service } from "@/lib/types";

/** Ecommerce mega-menu entries that link to existing service and migration pages. */
export const ecommerceNavServices: Service[] = [
  {
    slug: "ai-lead-site",
    number: "—",
    title: "Shopify Development",
    group: "Ecommerce",
    category: "Ecommerce",
    icon: "ecommerce",
    shortDescription: "Custom Shopify themes, product pages, and checkout flows.",
    whatItIs: "",
    deliverables: [],
    idealClients: [],
    processSteps: [],
    results: [],
    pricingSignal: "",
    timeline: "",
    image: "",
    order: 1,
  },
  {
    slug: "crm-pipeline-automation",
    number: "—",
    title: "Klaviyo Email Flows",
    group: "Ecommerce",
    category: "Ecommerce",
    icon: "crm",
    shortDescription: "Welcome, cart recovery, and post-purchase email sequences.",
    whatItIs: "",
    deliverables: [],
    idealClients: [],
    processSteps: [],
    results: [],
    pricingSignal: "",
    timeline: "",
    image: "",
    order: 2,
  },
  {
    slug: "ops-automation",
    number: "—",
    title: "Cart Abandonment Automation",
    group: "Ecommerce",
    category: "Ecommerce",
    icon: "automation",
    shortDescription: "Recover abandoned carts with timed email and SMS follow-up.",
    whatItIs: "",
    deliverables: [],
    idealClients: [],
    processSteps: [],
    results: [],
    pricingSignal: "",
    timeline: "",
    image: "",
    order: 3,
  },
  {
    slug: "shopify-to-headless-shopify",
    number: "—",
    title: "Headless Shopify Development",
    group: "Ecommerce",
    category: "Ecommerce",
    icon: "lead-site",
    shortDescription: "Custom Next.js storefront on top of Shopify checkout.",
    whatItIs: "",
    deliverables: [],
    idealClients: [],
    processSteps: [],
    results: [],
    pricingSignal: "",
    timeline: "",
    image: "",
    order: 4,
  },
];
