import type { Industry, IndustryCategory, PopularServiceLink } from "@/lib/types";
import { industryParents } from "@/lib/content/industry-parents";

function parentServices(parentSlug: string): PopularServiceLink[] {
  return industryParents.find((p) => p.slug === parentSlug)?.popularServices ?? [];
}

function sub(
  parentSlug: string,
  category: IndustryCategory,
  data: Omit<Industry, "parentSlug" | "category" | "popularServices"> & {
    popularServices?: PopularServiceLink[];
  },
): Industry {
  return {
    ...data,
    parentSlug,
    category,
    popularServices: data.popularServices ?? parentServices(parentSlug),
  };
}

export const industries: Industry[] = [
  sub("healthcare-clinics", "Healthcare Clinics", {
    slug: "dental-clinics",
    title: "Dental Clinics",
    whoItIsFor: "General and specialty dental practices with busy front desks.",
    whatWeBuild: "Dental websites, online booking, hygiene recall, and review automation.",
    problemSolved: "New-patient calls get missed and recall visits are not booked consistently.",
    heroHeadline: "Websites and booking automation for dental clinics.",
    hook: "Dental practices losing calls during chair time.",
    shortDescription: "Dental clinic websites, booking, intake, recall automation, and Google review requests.",
    painPoints: [
      { title: "New-patient calls get dropped", description: "Callers book elsewhere when nobody answers." },
      { title: "Hygiene recall is manual", description: "Overdue patients are not contacted on a schedule." },
    ],
    exampleProject: "Dental site with online booking, recall texts, and post-visit review requests.",
    commonUseCase: "A new patient books a cleaning online and gets reminder texts before the visit.",
    icon: "dental",
    order: 1,
  }),
  sub("healthcare-clinics", "Healthcare Clinics", {
    slug: "medical-clinics",
    title: "Medical Clinics",
    whoItIsFor: "Primary care and specialty medical clinics with high call volume.",
    whatWeBuild: "Medical websites, patient intake, booking, and SMS reminders.",
    problemSolved: "Patients wait on hold and intake paperwork slows every visit.",
    heroHeadline: "Patient intake and booking for medical clinics.",
    hook: "Medical clinics with overloaded phone lines.",
    shortDescription: "Medical clinic websites, intake forms, appointment booking, and automated reminders.",
    painPoints: [
      { title: "Phone lines stay busy", description: "Patients cannot reach the front desk quickly." },
      { title: "Intake slows check-in", description: "Paper forms create bottlenecks at arrival." },
    ],
    exampleProject: "Medical clinic site with online intake and appointment reminders.",
    commonUseCase: "A patient completes intake on their phone before arriving for the appointment.",
    icon: "medical",
    order: 2,
  }),
  sub("healthcare-clinics", "Healthcare Clinics", {
    slug: "peptide-clinics",
    title: "Peptide Clinics",
    whoItIsFor: "Peptide and wellness therapy clinics selling consults online.",
    whatWeBuild: "Consultation landing pages, booking, intake, and follow-up emails.",
    problemSolved: "Form fills go cold before a consultation is booked.",
    heroHeadline: "Landing pages and booking for peptide clinics.",
    hook: "Peptide clinics that need faster consult booking.",
    shortDescription: "Peptide clinic websites, consult booking, intake forms, and automated follow-up.",
    painPoints: [
      { title: "Leads go cold overnight", description: "Weekend inquiries wait until Monday to hear back." },
    ],
    exampleProject: "Peptide consult landing page with instant SMS and online booking.",
    commonUseCase: "A lead submits a form and gets a same-day text with a booking link.",
    icon: "peptide",
    order: 3,
  }),
  sub("healthcare-clinics", "Healthcare Clinics", {
    slug: "trt-clinics",
    title: "TRT Clinics",
    whoItIsFor: "TRT and hormone therapy clinics competing online.",
    whatWeBuild: "TRT websites, qualification forms, booking, and nurture emails.",
    problemSolved: "Prospects compare clinics online and book with whoever responds first.",
    heroHeadline: "Lead capture and booking for TRT clinics.",
    hook: "TRT clinics that need faster lead response.",
    shortDescription: "TRT clinic websites, qualification forms, AI phone assistants, and booking automation.",
    painPoints: [
      { title: "Slow lead response", description: "Prospects move to the next clinic in search results." },
    ],
    exampleProject: "TRT site with pricing FAQ, consult booking, and same-day SMS follow-up.",
    commonUseCase: "A prospect requests info and books a consult the same day via SMS link.",
    icon: "trt",
    order: 4,
  }),
  sub("healthcare-clinics", "Healthcare Clinics", {
    slug: "longevity-clinics",
    title: "Longevity Clinics",
    whoItIsFor: "Longevity and anti-aging clinics selling memberships and programs.",
    whatWeBuild: "Premium clinic sites, membership pages, booking, and renewal reminders.",
    problemSolved: "The website does not match the premium offer and renewals are tracked manually.",
    heroHeadline: "Premium websites and booking for longevity clinics.",
    hook: "Longevity clinics selling memberships and advanced diagnostics.",
    shortDescription: "Longevity clinic websites, membership pages, booking, and automated renewal reminders.",
    painPoints: [
      { title: "Website undersells the offer", description: "Prospects expect a polished experience before booking." },
    ],
    exampleProject: "Longevity clinic site with membership checkout and renewal email reminders.",
    commonUseCase: "A member renews online after an automated reminder sequence.",
    icon: "longevity",
    order: 5,
  }),
  sub("healthcare-clinics", "Healthcare Clinics", {
    slug: "med-spas",
    title: "Med Spas",
    whoItIsFor: "Med spas and aesthetic studios booking treatments by phone and online.",
    whatWeBuild: "Med spa websites, treatment booking, rebooking emails, and review automation.",
    problemSolved: "Bookings live in DMs and clients do not return for the next treatment.",
    heroHeadline: "Booking and rebooking automation for med spas.",
    hook: "Med spas relying on DMs and phone calls to fill rooms.",
    shortDescription: "Med spa websites, online booking, rebooking emails, and Google review automation.",
    painPoints: [
      { title: "Bookings live in DMs", description: "Messages get lost and staff cannot track availability." },
    ],
    exampleProject: "Med spa site with treatment booking and post-visit rebooking emails.",
    commonUseCase: "A client books a facial online and gets a rebooking offer two weeks later.",
    icon: "wellness",
    order: 6,
  }),
  sub("healthcare-clinics", "Healthcare Clinics", {
    slug: "aesthetic-clinics",
    title: "Aesthetic Clinics",
    whoItIsFor: "Cosmetic and aesthetic clinics selling consults for procedures.",
    whatWeBuild: "Treatment pages, galleries, consult booking, and follow-up automation.",
    problemSolved: "Prospects cannot compare treatments and pricing before they call.",
    heroHeadline: "Treatment pages and consult booking for aesthetic clinics.",
    hook: "Aesthetic clinics that need clearer consult conversion online.",
    shortDescription: "Aesthetic clinic websites, treatment landing pages, consult booking, and follow-up.",
    painPoints: [
      { title: "Treatment info is buried", description: "Prospects leave before understanding options and pricing." },
    ],
    exampleProject: "Aesthetic clinic site with treatment galleries and one-click consult booking.",
    commonUseCase: "A prospect reviews before-and-after photos and books a consult from the treatment page.",
    icon: "aesthetic",
    order: 7,
  }),
  sub("healthcare-clinics", "Healthcare Clinics", {
    slug: "wellness-clinics",
    title: "Wellness Clinics",
    whoItIsFor: "Wellness clinics offering IV, holistic, and integrative services.",
    whatWeBuild: "Wellness clinic websites, service pages, booking, and email follow-up.",
    problemSolved: "Services are hard to understand online and booking requires phone tag.",
    heroHeadline: "Service pages and booking for wellness clinics.",
    hook: "Wellness clinics with multiple services and manual booking.",
    shortDescription: "Wellness clinic websites, service pages, booking flows, and automated follow-up.",
    painPoints: [
      { title: "Services are confusing online", description: "Prospects do not know which service to book first." },
    ],
    exampleProject: "Wellness clinic site with clear service menu and online booking per treatment.",
    commonUseCase: "A visitor picks IV therapy from a service list and books a time slot online.",
    icon: "wellness-clinic",
    order: 8,
  }),

  sub("ecommerce-shopify", "Ecommerce & Shopify", {
    slug: "shopify-stores",
    title: "Shopify Stores",
    whoItIsFor: "Shopify merchants upgrading theme, checkout, and retention flows.",
    whatWeBuild: "Shopify development, product pages, cart recovery, and Klaviyo flows.",
    problemSolved: "The store converts poorly and repeat orders stay low.",
    heroHeadline: "Shopify development and conversion improvements.",
    hook: "Shopify stores with weak product pages and checkout drop-off.",
    shortDescription: "Shopify theme work, product page design, cart abandonment, and email flows.",
    painPoints: [{ title: "Low conversion", description: "Traffic arrives but product pages do not close the sale." }],
    exampleProject: "Shopify rebuild with new product pages and cart recovery emails.",
    commonUseCase: "A shopper returns via cart recovery email and completes checkout.",
    icon: "shopify",
    order: 9,
  }),
  sub("ecommerce-shopify", "Ecommerce & Shopify", {
    slug: "dtc-brands",
    title: "DTC Brands",
    whoItIsFor: "Direct-to-consumer brands selling one hero product or a small catalog.",
    whatWeBuild: "DTC websites, landing pages, Klaviyo flows, and post-purchase sequences.",
    problemSolved: "First purchase happens but second purchase does not.",
    heroHeadline: "Landing pages and retention for DTC brands.",
    hook: "DTC brands with high CAC and low repeat rate.",
    shortDescription: "DTC brand sites, landing pages, email flows, and post-purchase automation.",
    painPoints: [{ title: "One-time buyers", description: "Customers buy once and never hear a relevant follow-up." }],
    exampleProject: "DTC landing page with post-purchase education and second-order offer.",
    commonUseCase: "A buyer gets a timed email with usage tips and a reorder discount.",
    icon: "dtc",
    order: 10,
  }),
  sub("ecommerce-shopify", "Ecommerce & Shopify", {
    slug: "product-brands",
    title: "Product Brands",
    whoItIsFor: "Physical product brands launching SKUs direct to consumer.",
    whatWeBuild: "Product launch pages, Shopify stores, and announcement emails.",
    problemSolved: "New products launch without a dedicated page or email plan.",
    heroHeadline: "Launch pages and Shopify stores for product brands.",
    hook: "Product brands launching SKUs without a go-to-market page.",
    shortDescription: "Product launch pages, Shopify development, and email announcements.",
    painPoints: [{ title: "Rushed launches", description: "SKUs go live on a generic collection page." }],
    exampleProject: "Launch landing page and email sequence for a new SKU.",
    commonUseCase: "Subscribers get a launch email with a direct link to the new product page.",
    icon: "product",
    order: 11,
  }),
  sub("ecommerce-shopify", "Ecommerce & Shopify", {
    slug: "supplement-brands",
    title: "Supplement Brands",
    whoItIsFor: "Supplement and nutrition brands on Shopify with subscription offers.",
    whatWeBuild: "Supplement storefronts, subscription flows, and retention emails.",
    problemSolved: "Subscription churn happens without education or win-back messages.",
    heroHeadline: "Shopify and subscription flows for supplement brands.",
    hook: "Supplement brands with subscription churn.",
    shortDescription: "Supplement Shopify stores, subscription pages, and retention email flows.",
    painPoints: [{ title: "Subscription churn", description: "Month-two cancellations go unaddressed." }],
    exampleProject: "Supplement product page with subscription checkout and win-back emails.",
    commonUseCase: "A subscriber gets education emails before renewal and a win-back if they cancel.",
    icon: "supplement",
    order: 12,
  }),
  sub("ecommerce-shopify", "Ecommerce & Shopify", {
    slug: "wellness-ecommerce-brands",
    title: "Wellness Ecommerce Brands",
    whoItIsFor: "Wellness product companies selling devices, kits, and programs online.",
    whatWeBuild: "Wellness ecommerce sites, bundle pages, and onboarding emails.",
    problemSolved: "Complex products are hard to understand and bundles are poorly presented.",
    heroHeadline: "Ecommerce sites for wellness product brands.",
    hook: "Wellness brands selling kits and devices online.",
    shortDescription: "Wellness ecommerce websites, bundle pages, Klaviyo flows, and onboarding emails.",
    painPoints: [{ title: "Products need education", description: "Buyers need guidance before and after purchase." }],
    exampleProject: "Wellness store with bundle builder and post-purchase onboarding emails.",
    commonUseCase: "A buyer receives setup tips by email after purchasing a wellness device.",
    icon: "wellness-ecom",
    order: 13,
  }),
  sub("ecommerce-shopify", "Ecommerce & Shopify", {
    slug: "beauty-brands",
    title: "Beauty Brands",
    whoItIsFor: "Beauty and skincare brands selling DTC on Shopify.",
    whatWeBuild: "Beauty storefronts, routine quizzes, and retention email flows.",
    problemSolved: "Shoppers do not know which product to buy first.",
    heroHeadline: "Shopify stores and retention for beauty brands.",
    hook: "Beauty brands that need clearer product guidance online.",
    shortDescription: "Beauty brand Shopify sites, landing pages, and Klaviyo retention flows.",
    painPoints: [{ title: "Product choice overload", description: "Visitors leave without picking a starter product." }],
    exampleProject: "Beauty Shopify store with routine landing page and sample offer flow.",
    commonUseCase: "A visitor takes a short quiz and lands on a recommended starter set page.",
    icon: "beauty",
    order: 14,
  }),
  sub("ecommerce-shopify", "Ecommerce & Shopify", {
    slug: "fitness-product-brands",
    title: "Fitness Product Brands",
    whoItIsFor: "Fitness equipment and apparel brands selling online.",
    whatWeBuild: "Fitness ecommerce sites, product education pages, and post-purchase flows.",
    problemSolved: "Buyers need setup and usage guidance to reorder accessories.",
    heroHeadline: "Ecommerce for fitness product brands.",
    hook: "Fitness brands selling gear and programs online.",
    shortDescription: "Fitness product Shopify stores, education pages, and post-purchase email flows.",
    painPoints: [{ title: "Low accessory attach", description: "Customers buy the main product but not add-ons." }],
    exampleProject: "Fitness product site with setup videos and accessory upsell emails.",
    commonUseCase: "A buyer gets accessory recommendations by email after the main purchase.",
    icon: "fitness",
    order: 15,
  }),

  sub("small-business-custom-software", "Small Business Custom Software", {
    slug: "local-clinics",
    title: "Local Clinics",
    whoItIsFor: "Local clinics that need booking and intake without enterprise software.",
    whatWeBuild: "Clinic websites, booking flows, intake forms, and simple automations.",
    problemSolved: "Off-the-shelf tools do not fit how the clinic actually operates.",
    heroHeadline: "Custom booking and intake for local clinics.",
    hook: "Local clinics that need simple custom workflows.",
    shortDescription: "Websites, booking, intake, and light automations tailored to local clinics.",
    painPoints: [{ title: "Generic tools do not fit", description: "The team bends workflows around software limitations." }],
    exampleProject: "Local clinic site with custom intake and appointment rules.",
    commonUseCase: "A clinic books different visit types with separate intake forms per service.",
    icon: "local-clinic",
    order: 16,
  }),
  sub("small-business-custom-software", "Small Business Custom Software", {
    slug: "appointment-based-businesses",
    title: "Appointment-Based Businesses",
    whoItIsFor: "Salons, studios, consultants, and service businesses that run on appointments.",
    whatWeBuild: "Booking websites, calendars, reminders, and client follow-up.",
    problemSolved: "Scheduling happens by text and email with no central system.",
    heroHeadline: "Booking flows for appointment-based businesses.",
    hook: "Businesses scheduling everything manually by text.",
    shortDescription: "Booking websites, calendar integration, SMS reminders, and follow-up automation.",
    painPoints: [{ title: "Scheduling by text", description: "Availability and confirmations live in message threads." }],
    exampleProject: "Booking site with calendar sync and automated reminders.",
    commonUseCase: "A client books online and receives SMS reminders before the appointment.",
    icon: "appointment",
    order: 17,
  }),
  sub("small-business-custom-software", "Small Business Custom Software", {
    slug: "small-teams-manual-processes",
    title: "Small Teams With Manual Processes",
    whoItIsFor: "Teams of 2–20 people running operations in email and spreadsheets.",
    whatWeBuild: "Lightweight web apps, CRM automations, and workflow tooling.",
    problemSolved: "Everyone chases status updates instead of doing the work.",
    heroHeadline: "Automations for small teams stuck in manual processes.",
    hook: "Small teams coordinating work in email and spreadsheets.",
    shortDescription: "CRM automation, simple web apps, and workflow tooling for small teams.",
    painPoints: [{ title: "Status chasing", description: "The team spends hours asking where things stand." }],
    exampleProject: "Job tracker replacing a shared spreadsheet with notifications.",
    commonUseCase: "A job moves stages automatically and the client gets an email update.",
    icon: "team",
    order: 18,
  }),
  sub("small-business-custom-software", "Small Business Custom Software", {
    slug: "outgrowing-spreadsheets",
    title: "Businesses Outgrowing Spreadsheets",
    whoItIsFor: "Businesses whose spreadsheets now run sales, ops, or reporting.",
    whatWeBuild: "Dashboards, databases, and web apps that replace spreadsheet workflows.",
    problemSolved: "One wrong formula or duplicate row creates expensive mistakes.",
    heroHeadline: "Dashboards and web apps that replace spreadsheet workflows.",
    hook: "Teams whose spreadsheets became the database.",
    shortDescription: "Custom dashboards and web apps that replace spreadsheet-based workflows.",
    painPoints: [{ title: "Spreadsheet risk", description: "Version conflicts and formula errors create costly errors." }],
    exampleProject: "Sales dashboard fed by forms instead of manual spreadsheet updates.",
    commonUseCase: "A rep submits a form and the dashboard updates without anyone copying rows.",
    icon: "spreadsheet",
    order: 19,
  }),
  sub("small-business-custom-software", "Small Business Custom Software", {
    slug: "outgrowing-no-code-tools",
    title: "Businesses Outgrowing WordPress, Webflow, Wix, Squarespace, or Airtable",
    whoItIsFor: "Businesses that hit limits on no-code platforms and need custom code.",
    whatWeBuild: "Next.js websites, Sanity CMS, migrations, and custom features.",
    problemSolved: "The current platform cannot handle performance, SEO, or custom logic needs.",
    heroHeadline: "Migrations and custom builds when no-code tools hit limits.",
    hook: "Businesses that need custom code after outgrowing no-code platforms.",
    shortDescription: "Next.js development, Sanity CMS, and migrations from WordPress, Webflow, Wix, Squarespace, and Airtable.",
    painPoints: [{ title: "Platform limits", description: "Performance, SEO, or custom logic breaks on the current stack." }],
    exampleProject: "WordPress to Next.js migration with Sanity CMS for marketing pages.",
    commonUseCase: "A marketing team edits pages in Sanity while the site runs on Next.js.",
    icon: "migration",
    order: 20,
    popularServices: [
      { label: "Webflow to Next.js & Sanity", href: "/migrations/webflow-to-nextjs-sanity" },
      { label: "WordPress to Next.js & Sanity", href: "/migrations/wordpress-to-nextjs-sanity" },
      { label: "Framer to Next.js & Sanity", href: "/migrations/framer-to-nextjs-sanity" },
    ],
  }),
  sub("small-business-custom-software", "Small Business Custom Software", {
    slug: "portal-dashboard-booking-needs",
    title: "Businesses That Need a Portal, Dashboard, Booking Flow, or Internal Tool",
    whoItIsFor: "Businesses that need a login area, client portal, dashboard, or internal tool.",
    whatWeBuild: "Client portals, admin dashboards, booking flows, and internal tools.",
    problemSolved: "Clients call or email for updates that should live in a simple portal.",
    heroHeadline: "Portals, dashboards, and internal tools for small businesses.",
    hook: "Businesses that need a login area or internal tool built to spec.",
    shortDescription: "Client portals, admin dashboards, booking flows, and lightweight internal tools.",
    painPoints: [{ title: "Update requests by phone", description: "Clients ask for status that should be self-serve online." }],
    exampleProject: "Client portal with file upload, status timeline, and admin dashboard.",
    commonUseCase: "A client logs in, sees project status, and uploads requested documents.",
    icon: "portal",
    order: 21,
  }),
];
