import type { Service } from "@/lib/types";

export const services: Service[] = [
  {
    slug: "ai-lead-site",
    number: "01",
    title: "AI-Cited Lead Gen Site",
    group: "Websites",
    category: "SEO & AEO Content Systems",
    icon: "lead-site",
    shortDescription:
      "A lead gen site built to rank on Google and get cited by AI answer engines.",
    whatItIs:
      "A high-converting website on Next.js or Webflow, built so Google, ChatGPT, and Perplexity can find and cite your business. Schema markup, AEO-ready copy, Core Web Vitals performance, and a structure that turns traffic into booked calls.",
    deliverables: [
      "Custom design",
      "Next.js or Webflow build",
      "Schema markup & llms.txt",
      "AEO-ready copy",
      "CRM-connected lead capture",
      "WordPress or Webflow → Next.js migration (when needed)",
      "Analytics setup",
      "30-day post-launch support",
    ],
    idealClients: [
      "Service businesses whose site doesn't convert or show up in AI answers",
      "Teams on WordPress or Webflow ready to move to a faster Next.js stack",
      "Startups launching a first credible, discoverable web presence",
    ],
    processSteps: [
      { step: 1, title: "Map the funnel", description: "We define the one action every page should drive and design backward from it." },
      { step: 2, title: "Design the system", description: "Custom design built around your offer, not a template you fight against." },
      { step: 3, title: "Build for speed", description: "Next.js or Webflow, tuned for Core Web Vitals and schema from the first commit." },
      { step: 4, title: "Wire the capture", description: "Forms connect to your CRM with instant notification so no lead waits." },
    ],
    results: [
      "Sub-2-second load on mobile, the make-or-break for paid traffic",
      "Every lead in your CRM within seconds of submitting",
      "Pages structured to be cited in Google AI Overviews, ChatGPT, and Perplexity",
    ],
    pricingSignal: "$3,500",
    timeline: "3 to 5 weeks to launch",
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1600&auto=format&fit=crop",
    order: 1,
  },
  {
    slug: "ai-receptionist",
    number: "02",
    title: "AI Receptionist & Missed-Call Text-Back",
    group: "AI Tools",
    category: "Speed-to-Lead",
    icon: "receptionist",
    shortDescription: "Answer every call and missed call, 24/7, before they call your competitor.",
    whatItIs:
      "A 24/7 AI voice or chat system that answers inbound inquiries, qualifies leads, books appointments, and sends instant text-back to missed calls before they call your competitor.",
    deliverables: [
      "AI chat or voice agent configuration",
      "Missed-call SMS automation",
      "Lead qualification flow",
      "CRM integration",
      "Appointment booking",
      "Escalation-to-human rules",
    ],
    idealClients: [
      "HVAC, plumbing, and roofing teams who can't answer while on a job",
      "Dental and medical front desks drowning in inbound calls",
      "Legal and real estate offices where the first callback wins the client",
    ],
    processSteps: [
      { step: 1, title: "Script the intake", description: "We map the questions that qualify a lead and the answers that book the job." },
      { step: 2, title: "Build the agent", description: "Voice or chat agent configured to your services, hours, and tone." },
      { step: 3, title: "Wire missed-call text-back", description: "Every unanswered call triggers an instant SMS within seconds." },
      { step: 4, title: "Set escalation rules", description: "High-value or complex calls route to a human, the rest book themselves." },
    ],
    results: [
      "Missed calls answered by SMS in under 60 seconds",
      "Qualified appointments booked while your team works",
      "Fewer leads lost to the next contractor on the list",
    ],
    pricingSignal: "Starting from $1,200 setup + $299/mo",
    timeline: "5–10 days to live",
    image:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1600&auto=format&fit=crop",
    order: 2,
  },
  {
    slug: "crm-pipeline-automation",
    number: "05",
    title: "CRM & Pipeline Automation",
    group: "Automation",
    category: "Sales Infrastructure",
    icon: "crm",
    shortDescription: "A CRM your team stops managing and starts closing from.",
    whatItIs:
      "Full CRM setup on HubSpot, GoHighLevel, or Salesforce with automated pipeline stages, lead scoring, task creation, and follow-up sequences. Your team stops managing the tool and starts closing deals.",
    deliverables: [
      "CRM configuration",
      "Pipeline architecture",
      "Automated sequences",
      "Lead scoring",
      "Reporting dashboards",
      "Team training",
    ],
    idealClients: [
      "Teams whose deals live in inboxes, phone notes, and memory",
      "Owners who can't see pipeline value without asking three people",
      "Sales teams spending more time on data entry than selling",
    ],
    processSteps: [
      { step: 1, title: "Audit the pipeline", description: "We map how a lead actually moves from first touch to closed deal." },
      { step: 2, title: "Architect the stages", description: "Clear stages with entry and exit criteria, no ambiguity about what's next." },
      { step: 3, title: "Automate the busywork", description: "Tasks, follow-ups, and scoring fire automatically as deals progress." },
      { step: 4, title: "Train the team", description: "We document the workflow and train your team so adoption sticks." },
    ],
    results: [
      "Every lead scored and routed without manual triage",
      "Follow-up sequences that run whether or not anyone remembers",
      "A pipeline number you can trust at a glance",
    ],
    pricingSignal: "Starting from $2,500 setup",
    timeline: "2–4 weeks to launch",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop",
    order: 5,
  },
  {
    slug: "outbound-lead-gen",
    number: "03",
    title: "Outbound Lead Gen Automation",
    group: "Automation",
    category: "Pipeline Generation",
    icon: "outbound",
    shortDescription: "A system that puts only warm leads in front of your sales team.",
    whatItIs:
      "Scraping, enrichment, and AI-personalized outreach at scale. We build the system, prospect lists, personalization layers, and multi-channel sequences so your sales team only talks to warm leads.",
    deliverables: [
      "ICP definition",
      "Prospect list building",
      "Data enrichment pipeline",
      "AI personalization system",
      "Multi-channel sequence (email + LinkedIn)",
      "Reply management setup",
    ],
    idealClients: [
      "B2B teams whose outbound is manual and impossible to scale",
      "Founders doing their own prospecting between everything else",
      "Agencies and SaaS teams who need predictable pipeline",
    ],
    processSteps: [
      { step: 1, title: "Define the ICP", description: "We get specific about who buys, so the list is sharp from the start." },
      { step: 2, title: "Build and enrich", description: "Prospect lists scraped and enriched with the data that drives reply rates." },
      { step: 3, title: "Personalize at scale", description: "AI writes the opening line that makes each message feel hand-written." },
      { step: 4, title: "Run and manage", description: "Multi-channel sequences run, replies route to your team to close." },
    ],
    results: [
      "A repeatable list-to-reply pipeline instead of guesswork",
      "Personalization at volume without a team of SDRs",
      "Warm replies in your inbox, not cold lists to grind through",
    ],
    pricingSignal: "Starting from $3,000 setup + $500/mo management",
    timeline: "2–3 weeks to first sends",
    image:
      "https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=1600&auto=format&fit=crop",
    order: 3,
  },
  {
    slug: "seo-aeo-content",
    number: "04",
    title: "SEO & AEO Content Systems",
    group: "Websites",
    category: "Search & Answer Engines",
    icon: "seo",
    shortDescription: "Rank on Google and get cited in AI answers.",
    whatItIs:
      "We build the content and technical infrastructure to rank on Google and appear in AI-generated answers across ChatGPT, Perplexity, and Google AI Overviews. Schema markup, llms.txt, programmatic pages, and content that earns citations.",
    deliverables: [
      "Technical SEO audit",
      "Schema implementation",
      "llms.txt setup",
      "Keyword research",
      "Content briefs",
      "Monthly article delivery",
      "AEO optimization",
    ],
    idealClients: [
      "Businesses invisible on Google for the terms that matter",
      "Brands not yet cited in ChatGPT and Perplexity answers",
      "Teams publishing content that never ranks or converts",
    ],
    processSteps: [
      { step: 1, title: "Audit the foundation", description: "We fix the technical issues quietly capping your rankings." },
      { step: 2, title: "Structure for answers", description: "Schema and llms.txt make your content legible to AI engines." },
      { step: 3, title: "Research and brief", description: "We target terms with intent and brief content that earns citations." },
      { step: 4, title: "Publish and compound", description: "Monthly articles that build authority instead of one-off posts." },
    ],
    results: [
      "Rankings for terms your buyers actually search",
      "Citations in AI Overviews and answer engines",
      "Content that compounds in value month over month",
    ],
    pricingSignal: "Starting from $2,500 strategy + $1,500/mo content",
    timeline: "2 weeks to first publish",
    image:
      "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?q=80&w=1600&auto=format&fit=crop",
    order: 4,
  },
  {
    slug: "ops-automation",
    number: "06",
    title: "Internal Ops Automation",
    group: "Automation",
    category: "Operations",
    icon: "ops",
    shortDescription: "Eliminate the manual tasks quietly killing your team's time.",
    whatItIs:
      "We map your internal workflows, find the manual tasks killing your team's time, and automate them with n8n or Make. Reporting, document processing, scheduling, and internal notifications, handled automatically.",
    deliverables: [
      "Process audit",
      "Automation design",
      "n8n or Make workflow build",
      "Testing and documentation",
      "Team SOPs",
    ],
    idealClients: [
      "Teams copy-pasting data between tools every single day",
      "Operators whose reporting eats hours every week",
      "Businesses scaling headcount to handle work software should do",
    ],
    processSteps: [
      { step: 1, title: "Audit the workflow", description: "We watch how work actually moves and flag the manual chokepoints." },
      { step: 2, title: "Design the automation", description: "We map each task to a trigger, an action, and a fallback." },
      { step: 3, title: "Build and test", description: "Workflows built in n8n or Make, tested against real edge cases." },
      { step: 4, title: "Document and hand off", description: "Every workflow comes with an SOP so your team owns it." },
    ],
    results: [
      "Hours of weekly manual work removed per workflow",
      "Reports that build and send themselves",
      "Fewer errors from copy-paste and missed steps",
    ],
    pricingSignal: "Starting from $2,000 per workflow package",
    timeline: "1–3 weeks per workflow",
    image:
      "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?q=80&w=1600&auto=format&fit=crop",
    order: 6,
  },
  {
    slug: "custom-ai-agents",
    number: "07",
    title: "Custom AI Agents",
    group: "AI Tools",
    category: "Applied AI",
    icon: "agents",
    shortDescription: "Purpose-built agents for your knowledge, sales, and support.",
    whatItIs:
      "Purpose-built AI agents for your specific business: internal knowledge bases, sales enablement tools, support deflection bots, and document processing agents. Built on Claude API, OpenAI, or open-source models depending on your needs.",
    deliverables: [
      "Use case scoping",
      "Model selection",
      "Agent architecture",
      "Tool integrations",
      "System prompt engineering",
      "Testing",
      "Deployment",
      "Monitoring setup",
    ],
    idealClients: [
      "Teams whose knowledge lives in one person's head",
      "Support queues full of questions a bot could answer",
      "Operations buried in documents that need reading and routing",
    ],
    processSteps: [
      { step: 1, title: "Scope the use case", description: "We pin down the job to be done before writing a single prompt." },
      { step: 2, title: "Select the model", description: "Claude, OpenAI, or open-source, chosen for cost, speed, and accuracy." },
      { step: 3, title: "Build and integrate", description: "The agent gets the tools and data it needs to actually be useful." },
      { step: 4, title: "Test and monitor", description: "We harden it against failure modes and watch it in production." },
    ],
    results: [
      "Answers in seconds from sources that were buried",
      "Support volume deflected before it reaches a human",
      "Documents processed and routed without manual reading",
    ],
    pricingSignal: "Starting from $4,000",
    timeline: "4–8 weeks to deploy",
    image:
      "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1600&auto=format&fit=crop",
    order: 7,
  },
  {
    slug: "reporting-dashboards",
    number: "08",
    title: "Reporting Dashboards",
    group: "Automation",
    category: "Visibility",
    icon: "dashboards",
    shortDescription: "One live view of your whole business. No more tab-switching.",
    whatItIs:
      "One live view of your business: CRM pipeline, ad spend and ROAS, website traffic, revenue, and operational KPIs, pulled from your existing tools into a single dashboard. No more tab-switching.",
    deliverables: [
      "Tool audit",
      "Data pipeline architecture",
      "Dashboard build (Looker Studio, Metabase, or custom Next.js)",
      "Automated daily data refresh",
      "Alert setup",
    ],
    idealClients: [
      "Owners pulling numbers from five tools to see one picture",
      "Teams making decisions on week-old spreadsheets",
      "Operators who want one screen that tells the truth",
    ],
    processSteps: [
      { step: 1, title: "Audit the sources", description: "We inventory every tool that holds a number you care about." },
      { step: 2, title: "Build the pipeline", description: "Data flows automatically from each source into one place." },
      { step: 3, title: "Design the view", description: "The metrics that drive decisions, front and center, nothing else." },
      { step: 4, title: "Refresh and alert", description: "Daily refresh plus alerts when a number crosses a threshold." },
    ],
    results: [
      "One screen for pipeline, spend, traffic, and revenue",
      "Decisions made on today's data, not last week's",
      "Alerts that surface problems before they cost you",
    ],
    pricingSignal: "Starting from $1,500",
    timeline: "2 weeks to live dashboard",
    image:
      "https://images.unsplash.com/photo-1543286386-713bdd548da4?q=80&w=1600&auto=format&fit=crop",
    order: 8,
  },
  {
    slug: "review-reputation",
    number: "09",
    title: "Review & Reputation Automation",
    group: "Automation",
    category: "Local Reputation",
    icon: "reviews",
    shortDescription: "Your Google reputation on autopilot.",
    whatItIs:
      "An automated system that requests Google reviews at the right moment, responds with AI-assisted replies, flags negative feedback, and feeds your local SEO strategy. Your reputation on autopilot.",
    deliverables: [
      "Review request automation",
      "Google Business Profile optimization",
      "AI reply drafting system",
      "Negative review alert",
      "Monthly reputation report",
    ],
    idealClients: [
      "Local businesses leaving five-star reviews on the table",
      "Owners who forget to ask happy customers at the right moment",
      "Teams with no system to catch a bad review before it spreads",
    ],
    processSteps: [
      { step: 1, title: "Time the ask", description: "We trigger review requests at the moment satisfaction peaks." },
      { step: 2, title: "Optimize the profile", description: "Your Google Business Profile gets tuned for local ranking." },
      { step: 3, title: "Draft the replies", description: "AI drafts on-brand responses to every review for quick approval." },
      { step: 4, title: "Catch the negatives", description: "Negative feedback is flagged privately before it goes public." },
    ],
    results: [
      "A steady flow of new Google reviews each month",
      "Faster, consistent replies that improve local ranking",
      "Early warning on unhappy customers before they post",
    ],
    pricingSignal: "Starting from $800 setup + $199/mo",
    timeline: "1 week to automate",
    image:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1600&auto=format&fit=crop",
    order: 9,
  },
  {
    slug: "ai-systems-retainer",
    number: "10",
    title: "AI Systems Retainer",
    group: "Automation",
    category: "Ongoing Partnership",
    icon: "retainer",
    shortDescription: "We maintain, iterate, and expand your AI stack every month.",
    whatItIs:
      "An ongoing monthly partnership. We maintain, iterate, and expand your AI stack, adding new automations, improving agents, A/B testing sequences, and staying ahead of what's breaking or underperforming.",
    deliverables: [
      "Monthly strategy call",
      "Unlimited small fixes",
      "One new automation per month",
      "Performance reporting",
      "Priority response (24hr SLA)",
    ],
    idealClients: [
      "Businesses that want their systems to keep improving",
      "Owners who don't want to manage another vendor relationship",
      "Teams who'd rather expand the stack than babysit it",
    ],
    processSteps: [
      { step: 1, title: "Monthly strategy", description: "We meet to prioritize what moves the number this month." },
      { step: 2, title: "Ship one build", description: "At least one new automation or agent improvement every month." },
      { step: 3, title: "Fix and tune", description: "Unlimited small fixes and A/B tests on what's already live." },
      { step: 4, title: "Report and repeat", description: "Performance reporting so you always know what the stack returns." },
    ],
    results: [
      "A stack that improves every month instead of decaying",
      "Priority response with a 24-hour SLA",
      "One less vendor to chase, one more system that compounds",
    ],
    pricingSignal: "From $1,500/mo — 3-month minimum",
    timeline: "Ongoing monthly partnership",
    image:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1600&auto=format&fit=crop",
    order: 10,
  },
];
