import { defineField, defineType } from "sanity";
import { richTextMembers } from "../objects/extended";
import {
  flatOpenGraphFields,
  flatPrimaryCtaFields,
  flatSchemaFields,
  flatSeoFields,
  flatSettingsFields,
} from "../shared/flatFields";

export const caseStudy = defineType({
  name: "caseStudy",
  title: "Case study",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "relationships", title: "Relationships" },
    { name: "conversion", title: "Conversion" },
    { name: "seo", title: "SEO" },
    { name: "og", title: "Open Graph" },
    { name: "schema", title: "Schema" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "title",
      type: "string",
      group: "content",
      description: "Case study title.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "client",
      type: "string",
      title: "Client (legacy alias)",
      group: "content",
      description: "Legacy client field. Prefer clientName.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "clientName",
      type: "string",
      title: "Client name",
      group: "content",
      description: "Client or company name.",
    }),
    defineField({
      name: "clientLogo",
      type: "image",
      title: "Client logo",
      group: "content",
      description: "Client logo with alt text.",
      fields: [defineField({ name: "alt", type: "string", title: "Alt text" })],
    }),
    defineField({
      name: "clientWebsite",
      type: "url",
      title: "Client website",
      group: "content",
      description: "Client website URL.",
    }),
    defineField({
      name: "industry",
      type: "reference",
      to: [{ type: "industry" }, { type: "industryParent" }],
      group: "content",
      description: "Industry this case study belongs to.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "services",
      type: "array",
      title: "Services",
      group: "content",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "servicesUsed",
      type: "array",
      title: "Services used (legacy alias)",
      group: "content",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "summary",
      type: "text",
      rows: 3,
      group: "content",
      description: "Short case study summary.",
    }),
    defineField({
      name: "challenge",
      type: "array",
      title: "Challenge",
      group: "content",
      description: "Problem/challenge section in rich text.",
      of: richTextMembers,
    }),
    defineField({
      name: "solution",
      type: "array",
      title: "Solution",
      group: "content",
      description: "Solution section in rich text.",
      of: richTextMembers,
    }),
    defineField({
      name: "results",
      type: "array",
      title: "Results",
      group: "content",
      description: "Results section. Supports both caseResult objects and rich text.",
      of: [
        { type: "caseResult" },
        { type: "statItem" },
        ...richTextMembers,
      ],
    }),
    defineField({
      name: "resultStats",
      type: "array",
      title: "Result stats",
      group: "content",
      description: "Key result metrics with value, label, and description.",
      of: [{ type: "statItem" }],
    }),
    defineField({
      name: "deliverables",
      type: "array",
      title: "Deliverables",
      group: "content",
      of: [{ type: "deliverableItem" }],
    }),
    defineField({
      name: "screenshots",
      type: "array",
      title: "Screenshots",
      group: "content",
      of: [{ type: "mediaAsset" }],
    }),
    defineField({
      name: "beforeImages",
      type: "array",
      title: "Before images",
      group: "content",
      of: [{ type: "mediaAsset" }],
    }),
    defineField({
      name: "afterImages",
      type: "array",
      title: "After images",
      group: "content",
      of: [{ type: "mediaAsset" }],
    }),
    defineField({
      name: "testimonial",
      type: "reference",
      to: [{ type: "testimonial" }],
      group: "content",
    }),
    defineField({
      name: "testimonialId",
      type: "string",
      title: "Testimonial ID (legacy)",
      group: "content",
    }),
    defineField({
      name: "technologies",
      type: "array",
      title: "Technologies",
      group: "content",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({ name: "techStack", type: "array", title: "Tech stack (legacy)", group: "content", of: [{ type: "string" }] }),
    defineField({ name: "timeline", type: "string", group: "content" }),
    defineField({
      name: "projectYear",
      type: "number",
      title: "Project year",
      group: "content",
    }),
    defineField({
      name: "resultHeadline",
      type: "string",
      group: "content",
      description: "Headline result shown in hero.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "status",
      type: "string",
      group: "settings",
      options: { list: ["Published", "Draft", "Private"] },
      initialValue: "Published",
    }),
    defineField({
      name: "accent",
      type: "string",
      title: "Accent color (hex)",
      group: "content",
      initialValue: "#1c1917",
    }),
    defineField({
      name: "coverImage",
      type: "image",
      title: "Cover image",
      group: "content",
      description: "Main case study image.",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", type: "string", title: "Alt text" }),
        defineField({ name: "caption", type: "string", title: "Caption" }),
      ],
    }),
    defineField({ name: "coverImageUrl", type: "url", title: "Cover URL (legacy)", group: "content" }),
    defineField({ name: "image", type: "url", title: "Image URL (legacy alias)", group: "content" }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ references",
      group: "content",
      of: [{ type: "reference", to: [{ type: "faq" }] }],
    }),

    defineField({
      name: "relatedServices",
      type: "array",
      title: "Related services",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "relatedInsights",
      type: "array",
      title: "Related insights",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "post" }] }],
    }),
    defineField({
      name: "relatedPortfolioProjects",
      type: "array",
      title: "Related portfolio projects",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "portfolioProject" }] }],
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      title: "Related case studies",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),

    ...flatPrimaryCtaFields,

    ...flatSeoFields,
    ...flatOpenGraphFields,
    ...flatSchemaFields,
    ...flatSettingsFields,

    defineField({
      name: "tags",
      type: "array",
      group: "seo",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({ name: "seo", type: "seoFields", title: "SEO (grouped)", group: "seo" }),
  ],
  preview: {
    select: { title: "title", subtitle: "client", media: "coverImage" },
  },
});
