import { defineField, defineType } from "sanity";

export const caseStudy = defineType({
  name: "caseStudy",
  title: "Case study",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({ name: "client", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "industry",
      type: "reference",
      to: [{ type: "industry" }, { type: "industryParent" }],
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "servicesUsed",
      type: "array",
      title: "Services used",
      group: "content",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({ name: "timeline", type: "string", group: "content" }),
    defineField({ name: "resultHeadline", type: "string", group: "content" }),
    defineField({ name: "challenge", type: "text", rows: 5, group: "content" }),
    defineField({ name: "solution", type: "text", rows: 5, group: "content" }),
    defineField({
      name: "results",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "techStack",
      type: "array",
      title: "Tools used",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "workflow",
      type: "array",
      title: "Workflow",
      group: "content",
      of: [{ type: "workflowStep" }],
    }),
    defineField({
      name: "timelinePhases",
      type: "array",
      title: "Timeline phases",
      group: "content",
      of: [{ type: "timelinePhase" }],
    }),
    defineField({
      name: "screenshots",
      type: "array",
      title: "Screenshots",
      group: "content",
      of: [{ type: "caseStudyScreenshot" }],
    }),
    defineField({
      name: "testimonial",
      type: "reference",
      to: [{ type: "testimonial" }],
      group: "content",
    }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ",
      group: "content",
      of: [{ type: "articleFaq" }],
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),
    defineField({
      name: "relatedInsights",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "post" }] }],
    }),
    defineField({ name: "featured", type: "boolean", group: "content", initialValue: false }),
    defineField({ name: "accent", type: "string", group: "content", initialValue: "#1c1917" }),
    defineField({
      name: "coverImage",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          type: "string",
          title: "Alt text",
          validation: (r) => r.required().min(1).warning("Cover alt text improves SEO and accessibility"),
        }),
      ],
    }),
    defineField({ name: "seo", type: "seoFields", group: "seo" }),
  ],
  preview: { select: { title: "title", subtitle: "client", media: "coverImage" } },
});
