import { defineField, defineType } from "sanity";
import { richTextMembers } from "../objects/extended";
import {
  flatOpenGraphFields,
  flatPrimaryCtaFields,
  flatSchemaFields,
  flatSeoFields,
  flatSettingsFields,
} from "../shared/flatFields";

export const customSoftware = defineType({
  name: "customSoftware",
  title: "Custom software",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "section", title: "Section" },
    { name: "relationships", title: "Relationships" },
    { name: "conversion", title: "Conversion" },
    { name: "seo", title: "SEO" },
    { name: "og", title: "Open Graph" },
    { name: "schema", title: "Schema" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "title",
      type: "string",
      group: "content",
      description: "Custom software offer name.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
    }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 3,
      group: "content",
      description: "Short summary for cards.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "longDescription",
      type: "array",
      title: "Long description",
      group: "content",
      description: "Full description in rich text.",
      of: richTextMembers,
    }),
    defineField({
      name: "whatItIs",
      type: "text",
      rows: 4,
      title: "What it is (legacy)",
      group: "content",
    }),
    defineField({
      name: "softwareType",
      type: "string",
      title: "Software type",
      group: "content",
      options: {
        list: ["Dashboard", "Client Portal", "Internal Tool", "Automation App", "AI Tool", "Booking System", "CRM Extension", "API Integration"],
      },
    }),
    defineField({
      name: "targetAudience",
      type: "array",
      of: [{ type: "string" }],
      title: "Target audience",
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "problemSolved",
      type: "text",
      rows: 4,
      title: "Problem solved",
      group: "content",
      description: "Main problem the software solves.",
    }),
    defineField({
      name: "keyFeatures",
      type: "array",
      title: "Key features",
      group: "content",
      of: [{ type: "bulletItem" }],
    }),
    defineField({
      name: "whatsIncluded",
      type: "array",
      title: "What's included (legacy)",
      group: "content",
      of: [{ type: "featureBullet" }],
    }),
    defineField({
      name: "deliverables",
      type: "array",
      title: "Deliverables",
      group: "content",
      of: [{ type: "deliverableItem" }],
    }),
    defineField({
      name: "screenshots",
      type: "array",
      title: "Screenshots",
      group: "content",
      of: [{ type: "mediaAsset" }],
    }),
    defineField({
      name: "technologies",
      type: "array",
      of: [{ type: "string" }],
      title: "Technologies",
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "integrations",
      type: "array",
      of: [{ type: "string" }],
      title: "Integrations",
      group: "content",
      description: "Connected tools, APIs, and platforms.",
      options: { layout: "tags" },
    }),
    defineField({
      name: "process",
      type: "array",
      title: "Process",
      group: "content",
      of: [{ type: "processStep" }],
    }),
    defineField({
      name: "timeline",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "startingPrice",
      type: "number",
      title: "Starting price (USD)",
      group: "content",
    }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ references",
      group: "content",
      of: [{ type: "reference", to: [{ type: "faq" }] }],
    }),
    defineField({
      name: "coverImage",
      type: "image",
      title: "Cover image",
      group: "content",
      options: { hotspot: true },
    }),
    defineField({ name: "coverImageUrl", type: "url", title: "Cover URL (legacy)", group: "content" }),
    defineField({ name: "href", type: "string", group: "content", validation: (r) => r.required() }),

    /* Section grouping */
    defineField({ name: "sectionId", type: "string", title: "Section ID", group: "section" }),
    defineField({ name: "sectionLabel", type: "string", title: "Section label", group: "section" }),
    defineField({ name: "sectionHeadline", type: "string", title: "Section headline", group: "section" }),
    defineField({ name: "sectionDescription", type: "text", rows: 3, group: "section" }),
    defineField({ name: "sectionOrder", type: "number", group: "section" }),
    defineField({ name: "showInNav", type: "boolean", title: "Show in nav", group: "section", initialValue: true }),

    /* Relationships */
    defineField({
      name: "relatedServices",
      type: "array",
      title: "Related services",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "relatedIndustries",
      type: "array",
      title: "Related industries",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] }],
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      title: "Related case studies",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),
    defineField({
      name: "relatedPortfolioProjects",
      type: "array",
      title: "Related portfolio projects",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "portfolioProject" }] }],
    }),
    defineField({
      name: "relatedInsights",
      type: "array",
      title: "Related insights",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "post" }] }],
    }),

    ...flatPrimaryCtaFields,

    ...flatSeoFields,
    ...flatOpenGraphFields,
    ...flatSchemaFields,
    ...flatSettingsFields,

    defineField({
      name: "applicationCategory",
      type: "string",
      title: "Application category (schema)",
      group: "schema",
    }),
    defineField({
      name: "operatingSystem",
      type: "string",
      title: "Operating system (schema)",
      group: "schema",
      initialValue: "Web",
    }),
    defineField({
      name: "tags",
      type: "array",
      group: "seo",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({ name: "seo", type: "seoFields", title: "SEO (grouped)", group: "seo" }),
    defineField({
      name: "order",
      type: "number",
      group: "content",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "title", subtitle: "sectionLabel" } },
});
