import { defineField, defineType } from "sanity";

export const customSoftware = defineType({
  name: "customSoftware",
  title: "Custom software",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "navIcon", title: "Nav icon" },
    { name: "section", title: "Section" },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
    }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 3,
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({ name: "whatItIs", type: "text", rows: 4, group: "content" }),
    defineField({ name: "problemSolved", type: "text", rows: 4, group: "content" }),
    defineField({
      name: "targetAudience",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "keyFeatures",
      type: "array",
      group: "content",
      of: [{ type: "bulletItem" }],
    }),
    defineField({
      name: "whatsIncluded",
      type: "array",
      title: "What's included",
      group: "content",
      of: [{ type: "featureBullet" }],
    }),
    defineField({
      name: "deliverables",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "technologies",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "integrations",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "process",
      type: "array",
      group: "content",
      of: [{ type: "processStep" }],
    }),
    defineField({ name: "timeline", type: "string", group: "content" }),
    defineField({ name: "startingPrice", type: "number", group: "content" }),
    defineField({
      name: "softwareType",
      type: "string",
      group: "content",
      options: {
        list: [
          "Dashboard",
          "Client Portal",
          "Internal Tool",
          "Automation App",
          "AI Tool",
          "Booking System",
          "CRM Extension",
          "API Integration",
        ],
      },
    }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ",
      group: "content",
      of: [{ type: "articleFaq" }],
    }),
    defineField({
      name: "faqReferences",
      type: "array",
      title: "FAQ references",
      group: "content",
      of: [{ type: "reference", to: [{ type: "faq" }] }],
    }),
    defineField({
      name: "coverImage",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [defineField({ name: "alt", type: "string", title: "Alt text" })],
    }),
    defineField({ name: "href", type: "string", group: "content" }),
    defineField({ name: "order", type: "number", group: "content", validation: (r) => r.required() }),
    defineField({ name: "sectionId", type: "string", group: "section" }),
    defineField({ name: "sectionLabel", type: "string", group: "section" }),
    defineField({ name: "sectionHeadline", type: "string", group: "section" }),
    defineField({ name: "sectionDescription", type: "text", rows: 3, group: "section" }),
    defineField({ name: "sectionOrder", type: "number", group: "section" }),
    defineField({ name: "showInNav", type: "boolean", group: "section", initialValue: true }),
    defineField({
      name: "navIcon",
      type: "migrationPlatformIcon",
      title: "Nav icon",
      group: "navIcon",
    }),
    defineField({
      name: "relatedServices",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "relatedIndustries",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] }],
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),
    defineField({
      name: "relatedPortfolioProjects",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "portfolioProject" }] }],
    }),
    defineField({
      name: "relatedInsights",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "post" }] }],
    }),
    defineField({ name: "seo", type: "seoFields", group: "seo" }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "title", media: "coverImage" } },
});
