import { defineField, defineType } from "sanity";

export const faq = defineType({
  name: "faq",
  title: "FAQ",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "scope", title: "Scope" },
  ],
  fields: [
    defineField({
      name: "question",
      type: "string",
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "shortAnswer",
      type: "text",
      rows: 3,
      group: "content",
      description: "Direct answer shown on the site.",
    }),
    defineField({
      name: "answer",
      type: "text",
      rows: 5,
      group: "content",
      description: "Fallback plain-text answer if short answer is empty.",
    }),
    defineField({
      name: "category",
      type: "string",
      title: "FAQ category",
      group: "scope",
      options: {
        list: [
          "General",
          "Pricing",
          "Timeline",
          "Technical",
          "SEO",
          "AI / Automation",
          "CMS",
          "Support",
          "Migration",
          "Industry-specific",
          "Services",
          "Process",
          "Industries",
          "Migrations",
          "Custom Software",
          "Products",
          "Company",
        ],
      },
    }),
    defineField({
      name: "scopeServices",
      type: "array",
      title: "Applies to services",
      group: "scope",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "scopeIndustries",
      type: "array",
      title: "Applies to industries",
      group: "scope",
      of: [{ type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] }],
    }),
    defineField({
      name: "scopeMigrations",
      type: "array",
      title: "Applies to migrations",
      group: "scope",
      of: [{ type: "reference", to: [{ type: "migration" }] }],
    }),
    defineField({
      name: "tags",
      type: "array",
      group: "scope",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "order",
      type: "number",
      group: "content",
      description: "Sort order in FAQ listings.",
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "question", subtitle: "category" } },
});
