import { defineField, defineType } from "sanity";

const industryCategories = [
  { title: "Healthcare & Wellness", value: "Healthcare & Wellness" },
  { title: "Ecommerce & DTC", value: "Ecommerce & DTC" },
  { title: "Fitness, Coaching & Performance", value: "Fitness, Coaching & Performance" },
  { title: "Professional Services", value: "Professional Services" },
  { title: "B2B SaaS & Technology", value: "B2B SaaS & Technology" },
  { title: "Real Estate & Property", value: "Real Estate & Property" },
];

const sharedIndustryFields = [
  defineField({
    name: "title",
    type: "string",
    group: "content",
    validation: (r) => r.required(),
  }),
  defineField({
    name: "slug",
    type: "slug",
    group: "content",
    options: { source: "title", maxLength: 96 },
    validation: (r) => r.required(),
  }),
  defineField({
    name: "category",
    type: "string",
    group: "content",
    options: { list: industryCategories },
    validation: (r) => r.required(),
  }),
  defineField({
    name: "shortDescription",
    type: "text",
    rows: 2,
    group: "content",
    validation: (r) => r.required(),
  }),
  defineField({
    name: "industryOverview",
    type: "text",
    rows: 4,
    title: "Industry overview",
    group: "content",
  }),
  defineField({ name: "whoItIsFor", type: "text", rows: 3, group: "content", title: "Who it is for" }),
  defineField({ name: "whatWeBuild", type: "text", rows: 3, group: "content" }),
  defineField({ name: "problemSolved", type: "text", rows: 3, group: "content" }),
  defineField({ name: "heroHeadline", type: "string", group: "content" }),
  defineField({ name: "hook", type: "text", rows: 2, group: "content" }),
  defineField({
    name: "commonProblems",
    type: "array",
    title: "Common problems",
    group: "content",
    of: [{ type: "bulletItem" }],
  }),
  defineField({
    name: "painPoints",
    type: "array",
    title: "Pain points",
    group: "content",
    of: [{ type: "painPoint" }],
  }),
  defineField({
    name: "segmentSpecificProblems",
    type: "array",
    title: "Segment-specific problems",
    group: "content",
    of: [{ type: "bulletItem" }],
  }),
  defineField({
    name: "popularServices",
    type: "array",
    title: "Popular service links",
    group: "content",
    of: [{ type: "popularServiceLink" }],
  }),
  defineField({
    name: "servicesForThisIndustry",
    type: "array",
    title: "Recommended services",
    group: "content",
    of: [{ type: "reference", to: [{ type: "service" }] }],
  }),
  defineField({
    name: "faqs",
    type: "array",
    title: "FAQ",
    group: "content",
    of: [{ type: "articleFaq" }],
  }),
  defineField({
    name: "faqReferences",
    type: "array",
    title: "FAQ references",
    group: "content",
    of: [{ type: "reference", to: [{ type: "faq" }] }],
  }),
  defineField({ name: "exampleProject", type: "string", group: "content" }),
  defineField({ name: "commonUseCase", type: "string", group: "content" }),
  defineField({ name: "icon", type: "string", title: "Icon key", group: "content" }),
  defineField({
    name: "heroImage",
    type: "image",
    title: "Hero image",
    group: "content",
    options: { hotspot: true },
    fields: [
      defineField({ name: "alt", type: "string", title: "Alt text" }),
      defineField({ name: "caption", type: "string", title: "Caption" }),
    ],
  }),
  defineField({
    name: "coverImage",
    type: "image",
    title: "Cover image",
    group: "content",
    options: { hotspot: true },
    fields: [defineField({ name: "alt", type: "string", title: "Alt text" })],
  }),
  defineField({
    name: "relatedServices",
    type: "array",
    group: "relationships",
    of: [{ type: "reference", to: [{ type: "service" }] }],
  }),
  defineField({
    name: "relatedCaseStudies",
    type: "array",
    group: "relationships",
    of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
  }),
  defineField({
    name: "relatedInsights",
    type: "array",
    group: "relationships",
    of: [{ type: "reference", to: [{ type: "post" }] }],
  }),
  defineField({
    name: "tags",
    type: "array",
    group: "seo",
    of: [{ type: "reference", to: [{ type: "tag" }] }],
    options: { layout: "tags" },
  }),
  defineField({ name: "seo", type: "seoFields", group: "seo" }),
  defineField({ name: "order", type: "number", group: "content", validation: (r) => r.required() }),
  defineField({ name: "showInMainNav", type: "boolean", group: "nav", initialValue: false }),
  defineField({ name: "navOrder", type: "number", group: "nav" }),
  defineField({ name: "navTitle", type: "string", group: "nav" }),
  defineField({ name: "navShortDescription", type: "text", rows: 2, group: "nav" }),
];

export const industryParent = defineType({
  name: "industryParent",
  title: "Industry (parent)",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "nav", title: "Navigation" },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
  ],
  fields: [...sharedIndustryFields],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "title", subtitle: "category", media: "coverImage" } },
});

export const industry = defineType({
  name: "industry",
  title: "Industry segment",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "nav", title: "Navigation" },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    ...sharedIndustryFields,
    defineField({
      name: "parent",
      type: "reference",
      to: [{ type: "industryParent" }],
      group: "content",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "title", subtitle: "category", media: "coverImage" } },
});
