import { defineField, defineType } from "sanity";

export const migration = defineType({
  name: "migration",
  title: "Migration",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "platformIcons", title: "Platform icons" },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 3,
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "description",
      type: "text",
      rows: 4,
      title: "Hero description",
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({ name: "heroHeadline", type: "string", group: "content" }),
    defineField({ name: "heroSubhead", type: "text", rows: 3, group: "content" }),
    defineField({
      name: "fromIcons",
      type: "array",
      title: "From platform icons",
      group: "platformIcons",
      of: [{ type: "migrationPlatformIcon" }],
      validation: (r) => r.min(1).error("Add at least one source platform icon."),
    }),
    defineField({
      name: "toIcons",
      type: "array",
      title: "To platform icons",
      group: "platformIcons",
      of: [{ type: "migrationPlatformIcon" }],
      validation: (r) => r.min(1).error("Add at least one destination platform icon."),
    }),
    defineField({
      name: "whatsIncluded",
      type: "array",
      title: "What's included",
      group: "content",
      of: [{ type: "featureBullet" }],
    }),
    defineField({
      name: "deliverables",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "processSteps",
      type: "array",
      group: "content",
      of: [{ type: "processStep" }],
    }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ",
      group: "content",
      of: [{ type: "articleFaq" }],
    }),
    defineField({ name: "timeline", type: "string", group: "content" }),
    defineField({ name: "pricingSignal", type: "string", group: "content" }),
    defineField({
      name: "coverImage",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [defineField({ name: "alt", type: "string", title: "Alt text" })],
    }),
    defineField({
      name: "relatedServices",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "relatedIndustries",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] }],
    }),
    defineField({
      name: "relatedInsights",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "post" }] }],
    }),
    defineField({
      name: "relatedMigrations",
      type: "array",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "migration" }] }],
    }),
    defineField({
      name: "tags",
      type: "array",
      group: "seo",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({ name: "seo", type: "seoFields", group: "seo" }),
    defineField({
      name: "order",
      type: "number",
      group: "content",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "title", media: "coverImage" },
  },
});
