import { defineField, defineType } from "sanity";
import { richTextMembers } from "../objects/extended";
import {
  flatOpenGraphFields,
  flatSeoFields,
  flatSettingsFields,
} from "../shared/flatFields";

export const portfolioProject = defineType({
  name: "portfolioProject",
  title: "Portfolio project",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
    { name: "og", title: "Open Graph" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "title",
      type: "string",
      group: "content",
      description: "Portfolio project title.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "client",
      type: "string",
      title: "Client (legacy alias)",
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "clientName",
      type: "string",
      title: "Client name",
      group: "content",
      description: "Client or project owner name.",
    }),
    defineField({
      name: "projectType",
      type: "string",
      title: "Project type",
      group: "content",
      options: {
        list: ["Website", "Shopify", "Next.js", "Framer", "Automation", "AI Tool", "Dashboard", "Client Portal", "Migration"],
      },
    }),
    defineField({
      name: "category",
      type: "string",
      title: "Category (legacy alias)",
      group: "content",
      options: {
        list: ["Websites", "SaaS", "Real estate", "Nonprofit", "Ecommerce", "Healthcare", "Automation"],
      },
    }),
    defineField({
      name: "summary",
      type: "text",
      rows: 4,
      group: "content",
      description: "Short project summary.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 4,
      title: "Short description (alias)",
      group: "content",
    }),
    defineField({
      name: "longDescription",
      type: "array",
      title: "Long description",
      group: "content",
      description: "Full project description in rich text.",
      of: richTextMembers,
    }),
    defineField({
      name: "thumbnail",
      type: "image",
      title: "Thumbnail",
      group: "content",
      description: "Main project thumbnail with alt text and caption.",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", type: "string", title: "Alt text" }),
        defineField({ name: "caption", type: "string", title: "Caption" }),
      ],
    }),
    defineField({
      name: "coverImage",
      type: "image",
      title: "Cover image (legacy)",
      group: "content",
      options: { hotspot: true },
    }),
    defineField({ name: "coverImageUrl", type: "url", title: "Cover URL (legacy)", group: "content" }),
    defineField({ name: "image", type: "url", title: "Image URL (legacy alias)", group: "content" }),
    defineField({ name: "imageAlt", type: "string", title: "Cover alt text", group: "content" }),
    defineField({
      name: "gallery",
      type: "array",
      title: "Gallery",
      group: "content",
      of: [{ type: "mediaAsset" }],
    }),
    defineField({ name: "videoUrl", type: "url", title: "Hover video URL", group: "content" }),
    defineField({ name: "video", type: "url", title: "Video URL (legacy alias)", group: "content" }),
    defineField({ name: "href", type: "url", title: "Live URL (legacy alias)", group: "content" }),
    defineField({ name: "liveUrl", type: "url", title: "Live URL", group: "content", description: "Live project URL." }),
    defineField({ name: "previewUrl", type: "url", title: "Preview URL", group: "content", description: "Preview or staging URL." }),
    defineField({ name: "githubUrl", type: "url", title: "GitHub URL", group: "content" }),
    defineField({
      name: "accent",
      type: "string",
      group: "content",
      initialValue: "#1c1917",
    }),
    defineField({
      name: "year",
      type: "number",
      title: "Year",
      group: "content",
    }),
    defineField({ name: "logo", type: "portfolioLogo", group: "content" }),
    defineField({
      name: "features",
      type: "array",
      title: "Features",
      group: "content",
      of: [{ type: "bulletItem" }],
    }),
    defineField({
      name: "deliverables",
      type: "array",
      title: "Deliverables",
      group: "content",
      of: [{ type: "deliverableItem" }],
    }),
    defineField({
      name: "results",
      type: "array",
      title: "Results",
      group: "content",
      of: [{ type: "statItem" }],
    }),

    defineField({
      name: "services",
      type: "array",
      title: "Services",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "servicesUsed",
      type: "array",
      title: "Services used (legacy)",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "industries",
      type: "array",
      title: "Industries",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] }],
    }),
    defineField({
      name: "relatedIndustries",
      type: "array",
      title: "Related industries (legacy)",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] }],
    }),
    defineField({
      name: "testimonial",
      type: "reference",
      to: [{ type: "testimonial" }],
      group: "relationships",
    }),
    defineField({
      name: "relatedCaseStudy",
      type: "reference",
      to: [{ type: "caseStudy" }],
      title: "Related case study",
      group: "relationships",
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      title: "Related case studies (legacy)",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ references",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "faq" }] }],
    }),

    ...flatSeoFields,
    ...flatOpenGraphFields,
    ...flatSettingsFields,

    defineField({
      name: "tags",
      type: "array",
      group: "seo",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({ name: "seo", type: "seoFields", title: "SEO (grouped)", group: "seo" }),
    defineField({
      name: "order",
      type: "number",
      group: "settings",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "title", subtitle: "client", media: "coverImage" },
  },
});
