import { defineField, defineType } from "sanity";

const serviceGroups = [
  { title: "Lead-Gen Websites & AI Search", value: "Lead-Gen Websites & AI Search" },
  { title: "CRM & Follow-Up Automation", value: "CRM & Follow-Up Automation" },
  { title: "AI Receptionist & Booking Automation", value: "AI Receptionist & Booking Automation" },
  { title: "Custom Portals & Dashboards", value: "Custom Portals & Dashboards" },
  { title: "Platform Migrations", value: "Platform Migrations" },
  { title: "Monthly Support & Improvements", value: "Monthly Support & Improvements" },
  { title: "Websites (legacy)", value: "Websites" },
  { title: "Automation (legacy)", value: "Automation" },
  { title: "AI Tools (legacy)", value: "AI Tools" },
  { title: "Ecommerce (legacy)", value: "Ecommerce" },
];

export const service = defineType({
  name: "service",
  title: "Service",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "deliverables", title: "Deliverables & Pricing" },
    { name: "process", title: "Process & Results" },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({ name: "number", type: "string", title: "Number (01, 02…)", group: "content" }),
    defineField({
      name: "group",
      type: "string",
      group: "content",
      options: { list: serviceGroups },
      validation: (r) => r.required(),
    }),
    defineField({ name: "category", type: "string", title: "Category tag", group: "content" }),
    defineField({ name: "icon", type: "string", title: "Icon key", group: "content" }),
    defineField({
      name: "parentService",
      type: "string",
      title: "Parent service",
      group: "content",
      options: {
        list: [
          { title: "Lead-Gen Websites & AI Search", value: "lead-gen-websites" },
          { title: "CRM & Follow-Up Automation", value: "crm-automation" },
          { title: "AI Receptionist & Booking Automation", value: "ai-receptionist" },
          { title: "Custom Portals & Dashboards", value: "portals-dashboards" },
          { title: "Platform Migrations", value: "platform-migrations" },
          { title: "Monthly Support & Improvements", value: "monthly-support" },
        ],
      },
    }),
    defineField({
      name: "isFeatured",
      type: "boolean",
      title: "Featured on homepage",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "showOnHomepage",
      type: "boolean",
      title: "Show on homepage",
      group: "content",
      initialValue: true,
    }),
    defineField({
      name: "showInPrimaryServices",
      type: "boolean",
      title: "Show in primary services",
      group: "content",
      initialValue: true,
    }),
    defineField({
      name: "isLegacy",
      type: "boolean",
      title: "Legacy / hidden from primary surfaces",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "isSecondary",
      type: "boolean",
      title: "Secondary service",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "plainPromise",
      type: "text",
      title: "Plain promise (what it does, who it's for, what outcome)",
      rows: 2,
      group: "content",
    }),
    defineField({
      name: "problemSolved",
      type: "text",
      title: "Problem solved",
      rows: 2,
      group: "content",
    }),
    defineField({
      name: "bestFor",
      type: "array",
      title: "Best for",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 2,
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({ name: "whatItIs", type: "text", rows: 4, group: "content" }),
    defineField({ name: "heroHeadline", type: "string", group: "content" }),
    defineField({ name: "heroSubhead", type: "text", rows: 3, group: "content" }),
    defineField({
      name: "coverImage",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          type: "string",
          title: "Alt text",
          validation: (r) => r.required().min(1).warning("Cover alt text improves SEO and accessibility"),
        }),
        defineField({ name: "caption", type: "string", title: "Caption" }),
      ],
    }),
    defineField({
      name: "whatsIncluded",
      type: "array",
      title: "What's included",
      group: "deliverables",
      of: [{ type: "featureBullet" }],
    }),
    defineField({
      name: "deliverables",
      type: "array",
      group: "deliverables",
      of: [{ type: "string" }],
      title: "Deliverables",
    }),
    defineField({
      name: "idealClients",
      type: "array",
      group: "deliverables",
      of: [{ type: "string" }],
      title: "Who it's for",
    }),
    defineField({
      name: "pricingSignal",
      type: "string",
      group: "deliverables",
      title: "Pricing signal",
    }),
    defineField({
      name: "pricingTiers",
      type: "array",
      title: "Price tiers",
      group: "deliverables",
      of: [{ type: "priceTier" }],
    }),
    defineField({
      name: "startingPrice",
      type: "number",
      title: "Starting price (USD)",
      group: "deliverables",
    }),
    defineField({
      name: "monthlyPrice",
      type: "number",
      title: "Monthly price (USD)",
      group: "deliverables",
    }),
    defineField({
      name: "timeline",
      type: "string",
      group: "deliverables",
      title: "Typical timeline",
    }),
    defineField({
      name: "processSteps",
      type: "array",
      group: "process",
      of: [{ type: "processStep" }],
    }),
    defineField({
      name: "results",
      type: "array",
      group: "process",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ",
      group: "process",
      of: [{ type: "articleFaq" }],
    }),
    defineField({
      name: "relatedServices",
      type: "array",
      title: "Related services",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "relatedIndustries",
      type: "array",
      title: "Related industries",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] }],
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      title: "Related case studies",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),
    defineField({
      name: "relatedInsights",
      type: "array",
      title: "Related insights",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "post" }] }],
    }),
    defineField({
      name: "relatedMigrations",
      type: "array",
      title: "Related migrations",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "migration" }] }],
    }),
    defineField({
      name: "tags",
      type: "array",
      group: "seo",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({ name: "seo", type: "seoFields", group: "seo" }),
    defineField({
      name: "order",
      type: "number",
      group: "content",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "title", subtitle: "group", media: "coverImage" },
    prepare({ title, subtitle, media }) {
      return { title, subtitle, media };
    },
  },
});
