import { defineField, defineType } from "sanity";

export const serviceMegaMenuCard = defineType({
  name: "serviceMegaMenuCard",
  title: "Service mega menu card",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "relationships", title: "Relationships" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "title",
      type: "string",
      group: "content",
      description: "Card title shown in the mega menu.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "description",
      type: "text",
      rows: 3,
      title: "Description",
      group: "content",
      description: "Card description.",
    }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 3,
      title: "Short description (legacy alias)",
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "includes",
      type: "string",
      title: "Includes line",
      group: "content",
      description: "One-line summary of what's included.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "icon",
      type: "string",
      title: "Icon key",
      group: "content",
      description: "Icon name resolved by the frontend icon map.",
    }),
    defineField({
      name: "href",
      type: "string",
      title: "URL",
      group: "content",
      description: "Card destination URL.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "image",
      type: "image",
      title: "Card image",
      group: "content",
      description: "Card image with alt text and caption.",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", type: "string", title: "Alt text" }),
        defineField({ name: "caption", type: "string", title: "Caption" }),
      ],
    }),
    defineField({
      name: "badge",
      type: "string",
      title: "Badge",
      group: "content",
      description: 'Optional badge such as "New", "Popular", "Featured".',
    }),
    defineField({
      name: "group",
      type: "string",
      title: "Group",
      group: "content",
      description: "Which mega menu group this card belongs to.",
      options: {
        list: ["Websites", "Software", "Automation", "AI", "Ecommerce", "Migrations"],
      },
    }),
    defineField({
      name: "service",
      type: "reference",
      to: [{ type: "service" }],
      title: "Linked service",
      group: "relationships",
    }),
    defineField({
      name: "searchTags",
      type: "array",
      of: [{ type: "string" }],
      title: "Search tags",
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "featured",
      type: "boolean",
      title: "Featured",
      group: "settings",
      initialValue: false,
    }),
    defineField({
      name: "order",
      type: "number",
      group: "settings",
      description: "Sort order.",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "title", subtitle: "includes" } },
});
