import { defineField, defineType } from "sanity";

const serviceGroupValues = [
  "Lead-Gen Websites & AI Search",
  "CRM & Follow-Up Automation",
  "AI Receptionist & Booking Automation",
  "Custom In-House Software for SMBs",
  "Platform Migrations",
  "Monthly Support & Improvements",
  "Websites",
  "Automation",
  "AI Tools",
  "Ecommerce",
] as const;

const serviceGroups = serviceGroupValues.map((value) => ({ title: value, value }));

export const service = defineType({
  name: "service",
  title: "Service",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "deliverables", title: "Deliverables & Pricing" },
    { name: "process", title: "Process & Results" },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({ name: "number", type: "string", title: "Number (01, 02…)", group: "content" }),
    defineField({
      name: "group",
      type: "string",
      title: "Group",
      group: "content",
      options: { list: serviceGroups, layout: "dropdown" },
      validation: (r) => r.required().custom((value) => {
        if (!value) return true;
        return serviceGroupValues.includes(value as (typeof serviceGroupValues)[number])
          ? true
          : `Use one of the parent service groups (${serviceGroupValues.slice(0, 6).join(", ")}, …)`;
      }),
    }),
    defineField({ name: "category", type: "string", title: "Category tag", group: "content" }),
    defineField({ name: "icon", type: "string", title: "Icon key", group: "content" }),
    defineField({
      name: "parentService",
      type: "reference",
      title: "Parent service",
      group: "content",
      to: [{ type: "serviceMegaMenuCard" }],
      options: {
        disableNew: true,
        filter: "isLegacy != true",
      },
    }),
    defineField({
      name: "isFeatured",
      type: "boolean",
      title: "Featured on homepage",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "showOnHomepage",
      type: "boolean",
      title: "Show on homepage",
      group: "content",
      initialValue: true,
    }),
    defineField({
      name: "showInPrimaryServices",
      type: "boolean",
      title: "Show in primary services",
      group: "content",
      initialValue: true,
    }),
    defineField({
      name: "isLegacy",
      type: "boolean",
      title: "Legacy / hidden from primary surfaces",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "isSecondary",
      type: "boolean",
      title: "Secondary service",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "plainPromise",
      type: "text",
      title: "Plain promise (what it does, who it's for, what outcome)",
      rows: 2,
      group: "content",
    }),
    defineField({
      name: "problemSolved",
      type: "text",
      title: "Problem solved",
      rows: 2,
      group: "content",
    }),
    defineField({
      name: "bestFor",
      type: "array",
      title: "Best for",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 2,
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({ name: "whatItIs", type: "text", rows: 4, group: "content" }),
    defineField({ name: "heroHeadline", type: "string", group: "content" }),
    defineField({ name: "heroSubhead", type: "text", rows: 3, group: "content" }),
    defineField({
      name: "heroEyebrow",
      type: "string",
      title: "Hero eyebrow (focus keyword)",
      group: "content",
      description: "Short focus-keyword label shown above the H1 on the service detail page.",
    }),
    defineField({
      name: "focusKeyword",
      type: "string",
      title: "Focus keyword",
      group: "seo",
      description: "Primary SEO keyword for this service page.",
    }),
    defineField({
      name: "coverImage",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          type: "string",
          title: "Alt text",
          validation: (r) => r.required().min(1).warning("Cover alt text improves SEO and accessibility"),
        }),
        defineField({ name: "caption", type: "string", title: "Caption" }),
      ],
    }),
    defineField({
      name: "whatsIncluded",
      type: "array",
      title: "What's included",
      group: "deliverables",
      of: [{ type: "featureBullet" }],
    }),
    defineField({
      name: "problemsHeadline",
      type: "string",
      title: "Problems section headline",
      group: "deliverables",
      description: "Headline above the 6-reasons grid, e.g. “6 reasons your site is losing deals right now”.",
    }),
    defineField({
      name: "problems",
      type: "array",
      title: "Problems this service solves (6 cards)",
      group: "deliverables",
      description: "Six business-outcome problems shown as the '6 reasons' grid on the service page.",
      of: [{ type: "painPoint" }],
    }),
    defineField({
      name: "subServices",
      type: "array",
      title: "Sub-services (bento grid)",
      group: "deliverables",
      description: "Sub-service cards shown in the bento grid on the service detail page.",
      of: [{ type: "subServiceCard" }],
    }),
    defineField({
      name: "values",
      type: "array",
      title: "Agency values",
      group: "process",
      description: "Values showcased on the service detail page.",
      of: [{ type: "valueItem" }],
    }),
    defineField({
      name: "testimonials",
      type: "array",
      title: "Testimonials",
      group: "relationships",
      of: [{ type: "testimonialItem" }],
    }),
    defineField({
      name: "deliverables",
      type: "array",
      group: "deliverables",
      of: [{ type: "string" }],
      title: "Deliverables",
    }),
    defineField({
      name: "idealClients",
      type: "array",
      group: "deliverables",
      of: [{ type: "string" }],
      title: "Who it's for",
    }),
    defineField({
      name: "pricingSignal",
      type: "string",
      group: "deliverables",
      title: "Pricing signal",
    }),
    defineField({
      name: "pricingTiers",
      type: "array",
      title: "Price tiers",
      group: "deliverables",
      of: [{ type: "priceTier" }],
    }),
    defineField({
      name: "startingPrice",
      type: "number",
      title: "Starting price (USD)",
      group: "deliverables",
    }),
    defineField({
      name: "monthlyPrice",
      type: "number",
      title: "Monthly price (USD)",
      group: "deliverables",
    }),
    defineField({
      name: "timeline",
      type: "string",
      group: "deliverables",
      title: "Typical timeline",
    }),
    defineField({
      name: "processSteps",
      type: "array",
      group: "process",
      of: [{ type: "processStep" }],
    }),
    defineField({
      name: "results",
      type: "array",
      group: "process",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "faqEyebrow",
      type: "string",
      title: "FAQ eyebrow (left column)",
      group: "process",
      description: "Small label above the FAQ headline, e.g. “FAQ”.",
    }),
    defineField({
      name: "faqHeadline",
      type: "string",
      title: "FAQ headline",
      group: "process",
    }),
    defineField({
      name: "faqSubtext",
      type: "text",
      title: "FAQ subtext",
      rows: 3,
      group: "process",
    }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ items (right column)",
      group: "process",
      of: [{ type: "articleFaq" }],
    }),
    defineField({
      name: "relatedServices",
      type: "array",
      title: "Related services",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "relatedIndustries",
      type: "array",
      title: "Related industries",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] }],
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      title: "Related case studies",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),
    defineField({
      name: "relatedInsights",
      type: "array",
      title: "Related insights",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "post" }] }],
    }),
    defineField({
      name: "relatedMigrations",
      type: "array",
      title: "Related migrations",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "migration" }] }],
    }),
    defineField({
      name: "tags",
      type: "array",
      group: "seo",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({ name: "seo", type: "seoFields", group: "seo" }),
    defineField({
      name: "order",
      type: "number",
      group: "content",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "title", subtitle: "group", media: "coverImage" },
    prepare({ title, subtitle, media }) {
      return { title, subtitle, media };
    },
  },
});
