import { defineField, defineType } from "sanity";

const navGroups = [
  { title: "Websites", value: "Websites" },
  { title: "Shopify & Ecommerce", value: "Shopify & Ecommerce" },
  { title: "Custom Software", value: "Custom Software" },
  { title: "Automation", value: "Automation" },
  { title: "AI Tools", value: "AI Tools" },
];

export const serviceNavItem = defineType({
  name: "serviceNavItem",
  title: "Service nav item",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "relationships", title: "Relationships" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "label",
      type: "string",
      title: "Label",
      group: "content",
      description: "Navigation item label shown in the mega menu.",
    }),
    defineField({
      name: "title",
      type: "string",
      title: "Title (legacy alias)",
      group: "content",
      description: "Legacy title field. Prefer label above.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "href",
      type: "string",
      title: "URL",
      group: "content",
      description: "Navigation destination (e.g. /services/ai-lead-site).",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "description",
      type: "text",
      rows: 2,
      title: "Description",
      group: "content",
      description: "Short description shown under the label in the mega menu.",
    }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 2,
      title: "Short description (legacy alias)",
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "icon",
      type: "string",
      title: "Icon key",
      group: "content",
      description: "Icon name resolved by the frontend icon map.",
    }),
    defineField({
      name: "badge",
      type: "string",
      title: "Badge",
      group: "content",
      description: 'Optional badge such as "New", "Popular", "Featured".',
    }),
    defineField({
      name: "navGroup",
      type: "string",
      title: "Nav group",
      group: "content",
      description: "Which column group this item appears under in the mega menu.",
      options: { list: navGroups },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "service",
      type: "reference",
      to: [{ type: "service" }],
      title: "Linked service",
      group: "relationships",
      description: "Optional reference to the service document.",
    }),
    defineField({
      name: "relatedMegaMenuCards",
      type: "array",
      title: "Related mega menu cards",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "serviceMegaMenuCard" }] }],
    }),
    defineField({
      name: "searchTags",
      type: "array",
      of: [{ type: "string" }],
      title: "Search tags",
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "isVisible",
      type: "boolean",
      title: "Visible in navigation",
      group: "settings",
      description: "Controls whether this item appears in the mega menu.",
      initialValue: true,
    }),
    defineField({
      name: "openInNewTab",
      type: "boolean",
      title: "Open in new tab",
      group: "settings",
      initialValue: false,
    }),
    defineField({
      name: "order",
      type: "number",
      group: "settings",
      description: "Sort order within the group.",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "title", subtitle: "navGroup" } },
});
