import { defineField, defineType } from "sanity";
import { richTextMembers } from "../objects/extended";
import {
  flatConsultationCtaFields,
  flatOpenGraphFields,
  flatPrimaryCtaFields,
  flatQuickAnswerFields,
  flatSchemaFields,
  flatSeoFields,
  flatSettingsFields,
} from "../shared/flatFields";

const serviceGroups = [
  { title: "Websites", value: "Websites" },
  { title: "Automation", value: "Automation" },
  { title: "AI Tools", value: "AI Tools" },
  { title: "Ecommerce", value: "Ecommerce" },
];

export const service = defineType({
  name: "service",
  title: "Service",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "deliverables", title: "Deliverables & Pricing" },
    { name: "process", title: "Process & Results" },
    { name: "relationships", title: "Relationships" },
    { name: "aeo", title: "AEO" },
    { name: "conversion", title: "Conversion" },
    { name: "seo", title: "SEO" },
    { name: "og", title: "Open Graph" },
    { name: "schema", title: "Schema" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({ name: "title", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({ name: "number", type: "string", title: "Number (01, 02…)", group: "content" }),
    defineField({
      name: "group",
      type: "string",
      group: "content",
      options: { list: serviceGroups },
      validation: (r) => r.required(),
    }),
    defineField({ name: "category", type: "string", title: "Category tag", group: "content" }),
    defineField({ name: "icon", type: "string", title: "Icon key", group: "content" }),
    defineField({
      name: "shortDescription",
      type: "text",
      rows: 2,
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({ name: "whatItIs", type: "text", rows: 4, group: "content" }),
    defineField({ name: "heroHeadline", type: "string", group: "content" }),
    defineField({ name: "heroSubhead", type: "text", rows: 3, group: "content" }),
    defineField({ name: "heroEyebrow", type: "string", group: "content" }),
    defineField({ name: "heroTitle", type: "string", group: "content" }),
    defineField({ name: "heroDescription", type: "text", rows: 3, group: "content" }),
    defineField({ name: "oneSentencePitch", type: "string", group: "content" }),
    defineField({
      name: "longDescription",
      type: "array",
      title: "Long description",
      group: "content",
      of: richTextMembers,
    }),
    defineField({
      name: "coverImage",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", type: "string", title: "Alt text" }),
        defineField({ name: "caption", type: "string", title: "Caption" }),
      ],
    }),
    defineField({ name: "heroImage", type: "mediaAsset", group: "content" }),
    defineField({ name: "coverImageUrl", type: "url", title: "Cover URL (legacy)", group: "content" }),

    /* Deliverables & pricing */
    defineField({
      name: "whatsIncluded",
      type: "array",
      title: "What's included (rich)",
      group: "deliverables",
      of: [{ type: "featureBullet" }],
      description: "Used by the service detail page 'What's included' grid.",
    }),
    defineField({
      name: "deliverables",
      type: "array",
      group: "deliverables",
      of: [{ type: "string" }],
      title: "Deliverables (plain bullets)",
    }),
    defineField({
      name: "idealClients",
      type: "array",
      group: "deliverables",
      of: [{ type: "string" }],
      title: "Who it's for",
    }),
    defineField({
      name: "pricingSignal",
      type: "string",
      group: "deliverables",
      title: "Pricing signal (one-line)",
    }),
    defineField({
      name: "pricingTiers",
      type: "array",
      title: "Price tiers",
      group: "deliverables",
      of: [{ type: "priceTier" }],
      description: "Optional structured pricing tiers.",
    }),
    defineField({
      name: "startingPrice",
      type: "number",
      title: "Starting price (USD)",
      group: "deliverables",
    }),
    defineField({
      name: "timeline",
      type: "string",
      group: "deliverables",
      title: "Typical timeline",
    }),

    /* Process & results */
    defineField({
      name: "processSteps",
      type: "array",
      group: "process",
      of: [{ type: "processStep" }],
    }),
    defineField({
      name: "results",
      type: "array",
      group: "process",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "faqs",
      type: "array",
      title: "FAQ (inline)",
      group: "process",
      of: [{ type: "articleFaq" }],
      description: "Renders with FAQPage JSON-LD on the service detail page.",
    }),
    defineField({
      name: "faqReferences",
      type: "array",
      title: "FAQ references",
      group: "process",
      of: [{ type: "reference", to: [{ type: "faq" }] }],
    }),
    defineField({
      name: "inlineFaqs",
      type: "array",
      of: [{ type: "inlineFaq" }],
      group: "process",
    }),

    /* Positioning */
    defineField({
      name: "targetAudience",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "idealFor",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "notIdealFor",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "painPoints",
      type: "array",
      of: [{ type: "bulletItem" }],
      group: "content",
    }),
    defineField({
      name: "outcomes",
      type: "array",
      of: [{ type: "bulletItem" }],
      group: "content",
    }),
    defineField({
      name: "benefits",
      type: "array",
      of: [{ type: "bulletItem" }],
      group: "content",
    }),
    defineField({
      name: "useCases",
      type: "array",
      of: [{ type: "bulletItem" }],
      group: "content",
    }),
    defineField({
      name: "toolsUsed",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "technologies",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "includedFeatures",
      type: "array",
      of: [{ type: "featureBullet" }],
      group: "deliverables",
    }),
    defineField({
      name: "deliverableItems",
      type: "array",
      of: [{ type: "deliverableItem" }],
      group: "deliverables",
    }),
    defineField({
      name: "optionalAddons",
      type: "array",
      of: [{ type: "deliverableItem" }],
      group: "deliverables",
    }),
    defineField({
      name: "pricingNote",
      type: "string",
      group: "deliverables",
    }),
    defineField({
      name: "packages",
      type: "array",
      group: "deliverables",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "name", type: "string" }),
            defineField({ name: "price", type: "string" }),
            defineField({ name: "description", type: "text", rows: 2 }),
            defineField({ name: "timeline", type: "string" }),
            defineField({
              name: "features",
              type: "array",
              of: [{ type: "string" }],
            }),
            defineField({ name: "bestFor", type: "string" }),
            defineField({ name: "ctaLabel", type: "string" }),
            defineField({ name: "ctaHref", type: "string" }),
          ],
        },
      ],
    }),
    defineField({
      name: "body",
      type: "array",
      title: "Body (Portable Text)",
      group: "content",
      of: richTextMembers,
    }),
    defineField({
      name: "contentSections",
      type: "array",
      of: [{ type: "contentSection" }],
      group: "content",
    }),
    defineField({
      name: "requirements",
      type: "array",
      of: [{ type: "string" }],
      group: "deliverables",
    }),
    defineField({
      name: "clientInputsNeeded",
      type: "array",
      of: [{ type: "string" }],
      group: "deliverables",
    }),

    /* Relationships */
    defineField({
      name: "relatedServices",
      type: "array",
      title: "Related services",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "relatedIndustries",
      type: "array",
      title: "Related industries",
      group: "relationships",
      of: [
        { type: "reference", to: [{ type: "industry" }, { type: "industryParent" }] },
      ],
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      title: "Related case studies",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),
    defineField({
      name: "relatedInsights",
      type: "array",
      title: "Related insights / posts",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "post" }] }],
    }),
    defineField({
      name: "relatedMigrations",
      type: "array",
      title: "Related migrations",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "migration" }] }],
    }),
    defineField({
      name: "relatedProducts",
      type: "array",
      title: "Related products",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "product" }] }],
    }),
    defineField({
      name: "parentService",
      type: "reference",
      to: [{ type: "service" }],
      group: "relationships",
    }),
    defineField({
      name: "childServices",
      type: "array",
      of: [{ type: "reference", to: [{ type: "service" }] }],
      group: "relationships",
    }),

    /* AEO */
    defineField({ name: "quickAnswer", type: "aeoAnswerBlock", group: "aeo" }),
    defineField({ name: "aiSummary", type: "text", rows: 4, group: "aeo" }),
    defineField({ name: "llmSnippet", type: "text", rows: 4, group: "aeo" }),
    defineField({
      name: "searchIntent",
      type: "string",
      group: "aeo",
      options: {
        list: ["Informational", "Commercial", "Transactional", "Navigational"],
      },
    }),
    defineField({
      name: "commercialIntentKeywords",
      type: "array",
      of: [{ type: "string" }],
      group: "aeo",
      options: { layout: "tags" },
    }),
    defineField({
      name: "entitiesMentioned",
      type: "array",
      of: [{ type: "string" }],
      group: "aeo",
      options: { layout: "tags" },
    }),

    ...flatQuickAnswerFields,
    ...flatPrimaryCtaFields,
    ...flatConsultationCtaFields,

    /* Flat SEO / OG / Schema */
    ...flatSeoFields,
    ...flatOpenGraphFields,
    ...flatSchemaFields,
    ...flatSettingsFields,
    defineField({
      name: "serviceType",
      type: "string",
      title: "Service type (schema)",
      group: "schema",
    }),
    defineField({
      name: "areaServed",
      type: "array",
      of: [{ type: "string" }],
      title: "Area served (schema)",
      group: "schema",
    }),
    defineField({
      name: "providerName",
      type: "string",
      title: "Provider name (schema)",
      group: "schema",
    }),
    defineField({
      name: "priceRange",
      type: "string",
      title: "Price range (schema)",
      group: "schema",
    }),
    defineField({ name: "leadFormTitle", type: "string", title: "Lead form title", group: "conversion" }),
    defineField({ name: "leadFormDescription", type: "text", rows: 3, title: "Lead form description", group: "conversion" }),
    defineField({
      name: "tags",
      type: "array",
      group: "seo",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({ name: "seo", type: "seoFields", group: "seo" }),
    defineField({ name: "openGraph", type: "openGraphFields", group: "og" }),
    defineField({ name: "schemaMarkup", type: "schemaMarkupFields", group: "schema" }),
    defineField({
      name: "status",
      type: "string",
      group: "settings",
      options: { list: ["Active", "Draft", "Hidden"] },
      initialValue: "Active",
    }),

    defineField({
      name: "order",
      type: "number",
      group: "content",
      validation: (r) => r.required(),
    }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "title", subtitle: "group", status: "status", media: "coverImage" },
    prepare({ title, subtitle, status, media }) {
      return { title, subtitle: [subtitle, status].filter(Boolean).join(" · "), media };
    },
  },
});
