import { defineField, defineType } from "sanity";
import {
  flatOpenGraphFields,
  flatSeoFields,
} from "../shared/flatFields";

export const testimonial = defineType({
  name: "testimonial",
  title: "Testimonial",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "relationships", title: "Relationships" },
    { name: "seo", title: "SEO" },
    { name: "og", title: "Open Graph" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "clientName",
      type: "string",
      title: "Client name",
      group: "content",
      description: "Client full name.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "authorName",
      type: "string",
      title: "Author name (legacy alias)",
      group: "content",
      description: "Legacy field. Use clientName instead.",
    }),
    defineField({
      name: "clientRole",
      type: "string",
      title: "Client role",
      group: "content",
      description: "Client job title or role.",
    }),
    defineField({
      name: "authorTitle",
      type: "string",
      title: "Author title (legacy alias)",
      group: "content",
    }),
    defineField({
      name: "clientCompany",
      type: "string",
      title: "Client company",
      group: "content",
      description: "Client company name.",
    }),
    defineField({
      name: "company",
      type: "string",
      title: "Company (legacy alias)",
      group: "content",
    }),
    defineField({
      name: "clientImage",
      type: "image",
      title: "Client image",
      group: "content",
      description: "Client profile photo with alt text.",
      options: { hotspot: true },
      fields: [defineField({ name: "alt", type: "string", title: "Alt text" })],
    }),
    defineField({ name: "avatar", type: "image", title: "Avatar (legacy)", group: "content" }),
    defineField({ name: "avatarUrl", type: "url", title: "Avatar URL (legacy)", group: "content" }),
    defineField({
      name: "companyLogo",
      type: "image",
      title: "Company logo",
      group: "content",
      description: "Client company logo with alt text.",
      fields: [defineField({ name: "alt", type: "string", title: "Alt text" })],
    }),
    defineField({
      name: "quote",
      type: "text",
      rows: 4,
      group: "content",
      description: "Short testimonial quote shown on cards.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "fullTestimonial",
      type: "array",
      title: "Full testimonial",
      group: "content",
      description: "Longer testimonial content in rich text.",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "rating",
      type: "number",
      title: "Rating (1-5)",
      group: "content",
      description: "Rating value if available.",
      validation: (r) => r.min(1).max(5),
    }),
    defineField({
      name: "source",
      type: "string",
      title: "Source",
      group: "content",
      description: "Where the testimonial was collected.",
      options: { list: ["Upwork", "Fiverr", "Contra", "LinkedIn", "Direct", "Other"] },
    }),
    defineField({
      name: "platformSource",
      type: "string",
      title: "Platform source (legacy alias)",
      group: "content",
      options: { list: ["Upwork", "Clutch", "Google", "LinkedIn", "Direct", "Other"] },
    }),
    defineField({
      name: "sourceUrl",
      type: "url",
      title: "Source URL",
      group: "content",
      description: "Public source URL if available.",
    }),
    defineField({ name: "platformUrl", type: "url", title: "Source URL (legacy alias)", group: "content" }),
    defineField({
      name: "projectType",
      type: "string",
      title: "Project type",
      group: "content",
      description: "Type of project this testimonial is connected to.",
    }),
    defineField({ name: "industry", type: "string", group: "content" }),
    defineField({
      name: "platform",
      type: "boolean",
      title: "Platform review (homepage carousel)",
      group: "content",
      initialValue: false,
    }),

    defineField({
      name: "relatedService",
      type: "reference",
      to: [{ type: "service" }],
      title: "Related service",
      group: "relationships",
    }),
    defineField({
      name: "relatedServices",
      type: "array",
      title: "Related services (legacy)",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "service" }] }],
    }),
    defineField({
      name: "relatedIndustry",
      type: "reference",
      to: [{ type: "industry" }, { type: "industryParent" }],
      title: "Related industry",
      group: "relationships",
    }),
    defineField({
      name: "relatedCaseStudy",
      type: "reference",
      to: [{ type: "caseStudy" }],
      title: "Related case study",
      group: "relationships",
    }),
    defineField({
      name: "relatedCaseStudies",
      type: "array",
      title: "Related case studies (legacy)",
      group: "relationships",
      of: [{ type: "reference", to: [{ type: "caseStudy" }] }],
    }),
    defineField({
      name: "relatedPortfolioProject",
      type: "reference",
      to: [{ type: "portfolioProject" }],
      title: "Related portfolio project",
      group: "relationships",
    }),

    ...flatSeoFields,
    ...flatOpenGraphFields,

    defineField({
      name: "tags",
      type: "array",
      group: "seo",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "featured",
      type: "boolean",
      group: "settings",
      description: "Marks testimonial as featured for homepage highlights.",
      initialValue: false,
    }),
    defineField({
      name: "priority",
      type: "number",
      group: "settings",
    }),
    defineField({
      name: "permissionToShow",
      type: "boolean",
      title: "Permission to show",
      group: "settings",
      description: "Confirms the client has given permission to display this publicly.",
      initialValue: true,
    }),
    defineField({ name: "seo", type: "seoFields", title: "SEO (grouped)", group: "seo" }),
  ],
  preview: {
    select: { title: "clientName", subtitle: "clientCompany", media: "clientImage" },
  },
});
