import { SITE_ORIGIN } from "@/lib/site-url";

/** Plain-text robots.txt with guaranteed line breaks. */
export function GET(): Response {
  const body = [
    "User-agent: *",
    "Allow: /",
    "Disallow: /api/contact",
    "",
    "User-agent: GPTBot",
    "Allow: /",
    "",
    "User-agent: ChatGPT-User",
    "Allow: /",
    "",
    "User-agent: PerplexityBot",
    "Allow: /",
    "",
    "User-agent: Google-Extended",
    "Allow: /",
    "",
    "User-agent: ClaudeBot",
    "Allow: /",
    "",
    "User-agent: Claude-Web",
    "Allow: /",
    "",
    "User-agent: anthropic-ai",
    "Allow: /",
    "",
    "User-agent: Applebot-Extended",
    "Allow: /",
    "",
    "User-agent: Meta-ExternalAgent",
    "Allow: /",
    "",
    "User-agent: FacebookBot",
    "Allow: /",
    "",
    "User-agent: cohere-ai",
    "Allow: /",
    "",
    "User-agent: Bytespider",
    "Allow: /",
    "",
    "User-agent: CCBot",
    "Allow: /",
    "",
    `Host: ${SITE_ORIGIN}`,
    `Sitemap: ${SITE_ORIGIN}/sitemap.xml`,
    "",
    "# Machine-readable site index for AI systems",
    `# LLMs: ${SITE_ORIGIN}/llms.txt`,
    `# Full index: ${SITE_ORIGIN}/llms-full.txt`,
    "",
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
