import { writeFileSync } from "node:fs";
import { industries } from "../src/lib/content/industry-subs";

const lines = industries.map(
  (i) =>
    `  { source: "/industries/${i.slug}", destination: "/industries/${i.parentSlug}", permanent: true as const },`,
);

const content = `/** Auto-generated by scripts/generate-industry-sub-redirects.ts — do not edit manually. */
export const INDUSTRY_SUB_REDIRECTS = [
${lines.join("\n")}
] as const;
`;

writeFileSync("src/lib/content/industry-sub-redirects.ts", content, "utf8");
console.log(`Wrote ${industries.length} sub-industry redirects.`);
